module Moonlight.LinAlg.Dense
  ( Vector,
    Matrix,
    fromListVector,
    fromListMatrix,
    matrixRows,
    toListVector,
    toListMatrix,
    vectorLength,
    matrixShape,
    matrixToRows,
    DynVector,
    DynMatrix,
    DenseDoubleMatrix,
    mkDynVector,
    mkDynMatrix,
    mkDenseDoubleMatrixRowMajor,
    mkDenseDoubleMatrixRows,
    denseDoubleMatrixShape,
    denseDoubleMatrixToRowMajorVector,
    denseDoubleMatrixToRows,
    denseDoubleMatrixVectorProduct,
    dynMatrixFromRows,
    dynMatrixToRows,
    toDynVector,
    toDynMatrix,
    fromDynVector,
    fromDynMatrix,
    withDynVector,
    withDynMatrix,
    dynVectorLength,
    dynMatrixShape,
    dynVectorToList,
    dynMatrixToList,
    mapMatrix,
    add,
    mult,
    transpose,
  )
where

import Moonlight.LinAlg.Pure.Dense.Basic
  ( add,
    mapMatrix,
    mult,
    transpose,
  )
import Moonlight.LinAlg.Pure.Dense.Dynamic
  ( DynMatrix,
    DynVector,
    dynMatrixFromRows,
    dynMatrixShape,
    dynMatrixToList,
    dynMatrixToRows,
    dynVectorLength,
    dynVectorToList,
    fromDynMatrix,
    fromDynVector,
    mkDynMatrix,
    mkDynVector,
    toDynMatrix,
    toDynVector,
    withDynMatrix,
    withDynVector,
  )
import Moonlight.LinAlg.Pure.Dense.Flat
  ( DenseDoubleMatrix,
    denseDoubleMatrixShape,
    denseDoubleMatrixToRowMajorVector,
    denseDoubleMatrixToRows,
    denseDoubleMatrixVectorProduct,
    mkDenseDoubleMatrixRowMajor,
    mkDenseDoubleMatrixRows,
  )
import Moonlight.LinAlg.Pure.Dense.Types
  ( Matrix,
    Vector,
    fromListMatrix,
    fromListVector,
    matrixRows,
    matrixShape,
    matrixToRows,
    toListMatrix,
    toListVector,
    vectorLength,
  )
