
import EGraphKernel

namespace Moonlight.EGraph.Refinement

universe u v w

structure RepresentativeView (α : Type u) where
  canonicalRepresentative : α → α
  canonicalRepresentativeStable : ∀ value,
    canonicalRepresentative (canonicalRepresentative value) = canonicalRepresentative value

def RepresentativeView.toRepresentativeSystem {α : Type u}
    (view : RepresentativeView α) : Moonlight.EGraph.RepresentativeSystem α where
  repr := view.canonicalRepresentative
  repr_idempotent := view.canonicalRepresentativeStable

theorem representative_refines_find {α : Type u}
    (view : RepresentativeView α) (value : α) :
    view.canonicalRepresentative (view.canonicalRepresentative value) =
      view.canonicalRepresentative value :=
  Moonlight.EGraph.find_idempotent view.toRepresentativeSystem value

structure CanonicalizationView (α : Type u) (β : Type v) where
  equivalent : α → α → Prop
  canonicalize : α → β
  parent : β → β → β
  respects : ∀ {left right}, equivalent left right → canonicalize left = canonicalize right

def CanonicalizationView.toUnaryCongruence {α : Type u} {β : Type v}
    (view : CanonicalizationView α β) : Moonlight.EGraph.UnaryCongruence α β where
  equivalent := view.equivalent
  embed := view.canonicalize
  respects := view.respects

def CanonicalizationView.toBinaryRebuildSystem {α : Type u} {β : Type v}
    (view : CanonicalizationView α β) : Moonlight.EGraph.BinaryRebuildSystem α β where
  equivalent := view.equivalent
  canonicalize := view.canonicalize
  parent := view.parent
  respects := view.respects

theorem canonicalization_refines_congruence {α : Type u} {β : Type v}
    (view : CanonicalizationView α β) {left right : α} :
    view.equivalent left right → view.canonicalize left = view.canonicalize right :=
  Moonlight.EGraph.congruence_closure view.toUnaryCongruence

theorem canonicalization_refines_rebuild {α : Type u} {β : Type v}
    (view : CanonicalizationView α β)
    {leftParentChild leftCanonicalChild rightParentChild rightCanonicalChild : α} :
    view.equivalent leftParentChild leftCanonicalChild →
    view.equivalent rightParentChild rightCanonicalChild →
    view.parent (view.canonicalize leftParentChild) (view.canonicalize rightParentChild) =
    view.parent (view.canonicalize leftCanonicalChild) (view.canonicalize rightCanonicalChild) :=
  Moonlight.EGraph.rebuild_restores_congruence view.toBinaryRebuildSystem

/-!
The reference relation below is the intersection of every contextual
congruence containing the authored seeds whose regions cover the queried
context.  Consequently it is the least reflexive, symmetric, transitive,
congruence-closed relation generated by those seeds.  The compiled kernel only
stores edges; correctness is derived from local edge soundness, seed coverage,
and rebuild closure rather than being smuggled in as a field of the kernel.
-/

inductive ContextTerm (Atom : Type u) (Operator : Type v) where
  | atom : Atom → ContextTerm Atom Operator
  | node :
      Operator →
      ContextTerm Atom Operator →
      ContextTerm Atom Operator →
      ContextTerm Atom Operator

structure AuthoredRegionalSeed (Context : Type u) (Term : Type v) where
  region : Moonlight.EGraph.ContextRegion Context
  left : Term
  right : Term

def ActiveRegionalSeed {Context : Type u} {Term : Type v}
    (seeds : List (AuthoredRegionalSeed Context Term))
    (context : Context) (left right : Term) : Prop :=
  ∃ seed,
    seed ∈ seeds ∧
      seed.region context = true ∧
      seed.left = left ∧
      seed.right = right

structure ContextualCongruence
    (seeds : List (AuthoredRegionalSeed Context (ContextTerm Atom Operator)))
    (context : Context)
    (equivalent : ContextTerm Atom Operator → ContextTerm Atom Operator → Prop) : Prop where
  reflexive : ∀ value, equivalent value value
  symmetric : ∀ {left right}, equivalent left right → equivalent right left
  transitive :
    ∀ {left middle right},
      equivalent left middle → equivalent middle right → equivalent left right
  contains_authored_seed :
    ∀ {left right}, ActiveRegionalSeed seeds context left right → equivalent left right
  preserves_node :
    ∀ operator {leftFirst leftSecond rightFirst rightSecond},
      equivalent leftFirst rightFirst →
      equivalent leftSecond rightSecond →
      equivalent
        (.node operator leftFirst leftSecond)
        (.node operator rightFirst rightSecond)

def ReferenceContextualEquivalence
    (seeds : List (AuthoredRegionalSeed Context (ContextTerm Atom Operator)))
    (context : Context) (left right : ContextTerm Atom Operator) : Prop :=
  ∀ equivalent,
    ContextualCongruence seeds context equivalent → equivalent left right

theorem referenceContextualCongruence
    (seeds : List (AuthoredRegionalSeed Context (ContextTerm Atom Operator)))
    (context : Context) :
    ContextualCongruence seeds context (ReferenceContextualEquivalence seeds context) where
  reflexive := by
    intro value equivalent congruence
    exact congruence.reflexive value
  symmetric := by
    intro left right leftEquivalentRight equivalent congruence
    exact congruence.symmetric (leftEquivalentRight equivalent congruence)
  transitive := by
    intro left middle right leftEquivalentMiddle middleEquivalentRight equivalent congruence
    exact
      congruence.transitive
        (leftEquivalentMiddle equivalent congruence)
        (middleEquivalentRight equivalent congruence)
  contains_authored_seed := by
    intro left right activeSeed equivalent congruence
    exact congruence.contains_authored_seed activeSeed
  preserves_node := by
    intro operator leftFirst leftSecond rightFirst rightSecond
      firstEquivalent secondEquivalent equivalent congruence
    exact
      congruence.preserves_node
        operator
        (firstEquivalent equivalent congruence)
        (secondEquivalent equivalent congruence)

structure ContextualEquivalenceKernel
    (Context : Type u) (Atom : Type v) (Operator : Type w) where
  edge :
    Context →
      ContextTerm Atom Operator →
      ContextTerm Atom Operator →
      Prop

def KernelContextualEquivalent
    (kernel : ContextualEquivalenceKernel Context Atom Operator)
    (context : Context) :
    ContextTerm Atom Operator → ContextTerm Atom Operator → Prop :=
  Moonlight.EGraph.EquivalenceClosure (kernel.edge context)

theorem contextual_equivalence_kernel_correct
    (seeds : List (AuthoredRegionalSeed Context (ContextTerm Atom Operator)))
    (kernel : ContextualEquivalenceKernel Context Atom Operator)
    (edgeSound :
      ∀ {context left right},
        kernel.edge context left right →
          ReferenceContextualEquivalence seeds context left right)
    (authoredSeedsCovered :
      ∀ {context left right},
        ActiveRegionalSeed seeds context left right →
          KernelContextualEquivalent kernel context left right)
    (rebuildClosed :
      ∀ context operator {leftFirst leftSecond rightFirst rightSecond},
        KernelContextualEquivalent kernel context leftFirst rightFirst →
        KernelContextualEquivalent kernel context leftSecond rightSecond →
        KernelContextualEquivalent
          kernel
          context
          (.node operator leftFirst leftSecond)
          (.node operator rightFirst rightSecond))
    (context : Context) (left right : ContextTerm Atom Operator) :
    KernelContextualEquivalent kernel context left right ↔
      ReferenceContextualEquivalence seeds context left right := by
  constructor
  · intro kernelWitness
    induction kernelWitness with
    | refl value =>
        exact (referenceContextualCongruence seeds context).reflexive value
    | edge edgeWitness => exact edgeSound edgeWitness
    | symm _ equivalentWitness =>
        exact (referenceContextualCongruence seeds context).symmetric equivalentWitness
    | trans _ _ leftEquivalentMiddle middleEquivalentRight =>
        exact
          (referenceContextualCongruence seeds context).transitive
            leftEquivalentMiddle
            middleEquivalentRight
  · intro referenceWitness
    exact
      referenceWitness
        (KernelContextualEquivalent kernel context)
        { reflexive := Moonlight.EGraph.EquivalenceClosure.refl,
          symmetric := Moonlight.EGraph.EquivalenceClosure.symm,
          transitive := Moonlight.EGraph.EquivalenceClosure.trans,
          contains_authored_seed := authoredSeedsCovered,
          preserves_node := rebuildClosed context }

structure RestrictionEvidenceView (Context : Type u) (Section : Type v) where
  Reach : Context → Context → Type v
  identityEvidence : (context : Context) → Reach context context
  composeEvidence :
    {sourceContext midContext targetContext : Context} →
      Reach sourceContext midContext →
      Reach midContext targetContext →
      Reach sourceContext targetContext
  restrictAlong :
    {sourceContext targetContext : Context} →
      Reach sourceContext targetContext →
      Section →
      Section
  identityRestriction :
    ∀ {context} sectionValue,
      restrictAlong (identityEvidence context) sectionValue = sectionValue
  composedRestriction :
    ∀ {sourceContext midContext targetContext}
      (sourceEvidence : Reach sourceContext midContext)
      (targetEvidence : Reach midContext targetContext)
      (sectionValue : Section),
      restrictAlong targetEvidence (restrictAlong sourceEvidence sectionValue) =
        restrictAlong (composeEvidence sourceEvidence targetEvidence) sectionValue
  composeLeftIdentity :
    ∀ {sourceContext targetContext}
      (targetEvidence : Reach sourceContext targetContext),
      composeEvidence (identityEvidence sourceContext) targetEvidence = targetEvidence
  composeRightIdentity :
    ∀ {sourceContext targetContext}
      (sourceEvidence : Reach sourceContext targetContext),
      composeEvidence sourceEvidence (identityEvidence targetContext) = sourceEvidence
  composeAssociative :
    ∀ {sourceContext firstMidContext secondMidContext targetContext}
      (firstEvidence : Reach sourceContext firstMidContext)
      (secondEvidence : Reach firstMidContext secondMidContext)
      (thirdEvidence : Reach secondMidContext targetContext),
      composeEvidence (composeEvidence firstEvidence secondEvidence) thirdEvidence =
        composeEvidence firstEvidence (composeEvidence secondEvidence thirdEvidence)

def RestrictionEvidenceView.toRestrictionSystem {Context : Type u} {Section : Type v}
    (view : RestrictionEvidenceView Context Section) : Moonlight.EGraph.RestrictionSystem Context Section where
  Morphism := view.Reach
  identityMorphism := view.identityEvidence
  compose := view.composeEvidence
  restrict := view.restrictAlong
  identity := view.identityRestriction
  composes := view.composedRestriction
  compose_left_identity := view.composeLeftIdentity
  compose_right_identity := view.composeRightIdentity
  compose_associative := view.composeAssociative

theorem restriction_evidence_refines_composition {Context : Type u} {Section : Type v}
    (view : RestrictionEvidenceView Context Section)
    {sourceContext midContext targetContext : Context}
    (sourceEvidence : view.Reach sourceContext midContext)
    (targetEvidence : view.Reach midContext targetContext)
    (sectionValue : Section) :
    view.restrictAlong targetEvidence (view.restrictAlong sourceEvidence sectionValue) =
      view.restrictAlong (view.composeEvidence sourceEvidence targetEvidence) sectionValue :=
  Moonlight.EGraph.context_restriction_composition view.toRestrictionSystem sourceEvidence targetEvidence sectionValue

theorem restriction_evidence_refines_global_section {Context : Type u} {Section : Type v}
    (view : RestrictionEvidenceView Context Section)
    {rootContext reachableContext : Context}
    (reachEvidence : view.Reach rootContext reachableContext)
    (sectionValue : Section) :
    Moonlight.EGraph.IsGlobalSection view.toRestrictionSystem rootContext sectionValue →
    view.restrictAlong reachEvidence sectionValue = sectionValue ∧
      Moonlight.EGraph.IsGlobalSection view.toRestrictionSystem reachableContext sectionValue :=
  Moonlight.EGraph.context_global_section view.toRestrictionSystem reachEvidence sectionValue

structure ExtractionWitnessView (α : Type u) where
  eclass : Moonlight.EGraph.EClass α
  representative : α
  representativeInClass : eclass representative

def ExtractionWitnessView.toExtractionWitness {α : Type u}
    (view : ExtractionWitnessView α) : Moonlight.EGraph.ExtractionWitness α view.eclass where
  term := view.representative
  in_class := view.representativeInClass

theorem extraction_witness_refines_in_class {α : Type u}
    (view : ExtractionWitnessView α) :
    view.eclass view.representative :=
  Moonlight.EGraph.extract_in_class view.toExtractionWitness

structure ProofAdmissibilityView (Certificate : Type u) (Judgment : Type v) where
  admissible : Certificate → Judgment → Prop
  semanticallyValid : Judgment → Prop
  admissibilitySound : ∀ {certificate judgment},
    admissible certificate judgment → semanticallyValid judgment

def ProofAdmissibilityView.toProofSystem {Certificate : Type u} {Judgment : Type v}
    (view : ProofAdmissibilityView Certificate Judgment) : Moonlight.EGraph.ProofSystem Certificate Judgment where
  proves := view.admissible
  soundModel := view.semanticallyValid
  sound := view.admissibilitySound

theorem proof_admissibility_refines_soundness {Certificate : Type u} {Judgment : Type v}
    (view : ProofAdmissibilityView Certificate Judgment)
    {certificate : Certificate} {judgment : Judgment} :
    view.admissible certificate judgment → view.semanticallyValid judgment :=
  Moonlight.EGraph.proof_soundness view.toProofSystem

end Moonlight.EGraph.Refinement
