module Moonlight.EGraph.Introspection.Core.HsExpr
  ( HsVarRef (..),
    BinderAnn (..),
    HsPatF (..),
    patBinders,
    traversePatBinders,
    LetMode (..),
    LetRecursion (..),
    LetProvenance (..),
    ScopeId,
    ScopeIdFailure (..),
    ScopeCtx (..),
    ScopeIndex,
    ScopeIndexFailure (..),
    ScopeLookupFailure (..),
    FreeScopeSummary,
    mkScopeId,
    scopeIdKey,
    rootScopeId,
    mkScopeIndex,
    scopeIndexRoot,
    scopeParentId,
    scopeDepthOf,
    scopeIsAncestorOf,
    scopeComparable,
    scopeLca,
    scopeCtxLeq,
    scopeCtxMeet,
    scopeCtxJoin,
    scopeObservedCount,
    scopeObservedContexts,
    scopeTopCtx,
    scopeBottomCtx,
    binderIntroScope,
    binderSiteScope,
    emptyFreeScopeSummary,
    singletonFreeScopeSummary,
    mergeFreeScopeSummary,
    mergeFreeScopeSummaryBy,
    deleteFreeScopeSummary,
    freeScopeSummaryContains,
    freeScopeSummarySize,
    freeScopeSummaryToList,
    freeScopeSupportAnchor,
    NormalizedLit (..),
    normalizeHsLit,
    NormalizedOverLit (..),
    normalizeHsOverLit,
    NormalizedFieldLabel (..),
    normalizeFieldLabel,
    NormalizedTypeText (..),
    NormalizedArithSeq (..),
    HsOpaqueTag (..),
    HsPatOpaqueTag (..),
    HsExprF (..),
    HsStmtF (..),
    HsGuardStmtF (..),
    GuardedAltF (..),
    ScopedExpr (..),
    eraseScopedExpr,
    HsExprTag (..),
    TagSignature (..),
    tagSignatureFromTag,
    tagSignatureMember,
    HsExprAnalysis (..),
    HsExprAnalysisError (..),
    HsExprPipelineFailure (..),
    HsExprBindingExtractionMetrics (..),
    HsExprPipelineMetrics (..),
    hsExprBinderSubstAlgebra,
    etaReductionSpanFor,
    compositionSpanFor,
    betaReductionSpanFor,
    letReductionSpanFor,
    HsExprInsertionMetrics (..),
    HsExprInsertionError (..),
    HsExprContextLatticeError (..),
    HsExprSiteRuleError (..),
    InsertionSeeding (..),
    SpanClassRow (..),
    identityInsertionSeeding,
    HsExprSupportRuleMetrics (..),
    convertedModuleContextLattice,
    hsExprScopeGuardCapabilityResolver,
    hsExprCapabilityGenerationForContextGraph,
    hsExprRuntimeCapabilitiesForContextGraph,
    insertScopedExprWithSupport,
    insertConvertedModuleWithMetrics,
    insertConvertedModule,
    hsExprSupportRuleMetrics,
    HsExprSiteRuleKind (..),
    hsExprSupportedLawRules,
    hsExprSupportedRules,
    hsExprEtaLawId,
    hsExprCompositionLawId,
    hsExprBetaLawId,
    hsExprLetInlineLawId,
    hsExprBindingFrontLawId,
    hsExprComposeOracleKey,
    hsExprMapOracleKey,
    hsExprFmapOracleKey,
    hsExprFilterOracleKey,
    hsExprAppendOracleKey,
    hsExprConcatOracleKey,
    hsExprConcatMapOracleKey,
    hsExprReverseOracleKey,
    hsExprIdOracleKey,
    hsExprAndOracleKey,
    hsExprBindOracleKey,
    hsExprReturnOracleKey,
    hsExprPureOracleKey,
    hsExprPlusOracleKey,
    hsExprTimesOracleKey,
    hsExprMapFusionLawId,
    hsExprFmapFusionLawId,
    hsExprFilterFusionLawId,
    hsExprMapFilterInterchangeLawId,
    hsExprAppendRightIdentityLawId,
    hsExprAppendLeftIdentityLawId,
    hsExprAppendAssociativityLawId,
    hsExprMapAppendFactorLawId,
    hsExprConcatMapLawId,
    hsExprReverseInvolutionLawId,
    hsExprMapIdLawId,
    hsExprFmapIdLawId,
    hsExprMonadLeftIdentityLawId,
    hsExprMonadRightIdentityLawId,
    hsExprParErasureLawId,
    hsExprPlusAssociativityLawId,
    hsExprPlusCommutativityLawId,
    hsExprTimesAssociativityLawId,
    hsExprTimesCommutativityLawId,
    hsExprPlusUnitLawId,
    hsExprTimesUnitLawId,
    hsExprLawfulFunctorFactId,
    hsExprLawfulMonadFactId,
    hsExprLawfulNumTypeFactId,
    hsExprEvidenceFactRulesFor,
    HsExprNameTable (..),
    HsExprVocabularyRuleMetrics (..),
    hsExprOracleKeyTable,
    hsExprVocabularyLawIds,
    hsAcceptedComposeOrigins,
    hsAcceptedMapOrigins,
    hsAcceptedFmapOrigins,
    hsAcceptedFilterOrigins,
    hsAcceptedAppendOrigins,
    hsAcceptedConcatOrigins,
    hsAcceptedConcatMapOrigins,
    hsAcceptedReverseOrigins,
    hsAcceptedIdOrigins,
    hsAcceptedAndOrigins,
    hsAcceptedBindOrigins,
    hsAcceptedReturnOrigins,
    hsAcceptedPureOrigins,
    hsAcceptedPlusOrigins,
    hsAcceptedTimesOrigins,
    hsLawfulFunctorInstanceOrigins,
    hsLawfulMonadInstanceOrigins,
    hsLawfulNumTypeWords,
    hsExprLawRuleIdBase,
    hsExprSiteLawFamily,
    hsExprParErasureLawFamily,
    hsExprRenamerLawFamily,
    hsExprSelfUnfoldLawId,
    hsExprSelfUnfoldRuleIdBase,
    SelfLawRefusal (..),
    SelfLawRow (..),
    hsExprSelfUnfoldLawFamily,
    HsExprBindingSig (..),
    SurfaceName (..),
    HsExprBindingRule,
    HsExprBindingFactRule,
    HsExprBindingFrontError (..),
    HsExprBindingRuleMetrics (..),
    HsExprBindingCorpus (..),
    hsExprBindingRuleIdBase,
    hsExprSubstitutionAllowedFactId,
    hsExprBindingRelations,
    hsExprScopedBindingSyntax,
    hsExprBindingLanguageSyntax,
    hsExprFresheningSyntax,
    hsExprChildBinderEdges,
    hsExprBindingCorpus,
    HsExprSig (..),
    HsExprSigTag (..),
    HsExprTerm,
    HsExprLawEmitError (..),
    HsExprFoldError (..),
    emitExpr,
    foldNodeToHsExprF,
    foldGuardTermToHsExprF,
    foldRewriteConditionToHsExprF,
    foldApplicationConditionToHsExprF,
    collectTags,
    matchesHsExprPattern,
    matchesHsExprSpanLhs,
    applyHsExprSpanAtRoot,
    hsExprDiagnosticSpans,
    analyzeHaskellSource,
    measureConvertedModuleInsertionMetrics,
    measureHaskellSourceInsertionMetrics,
    measureConvertedModulePipeline,
    measureHaskellSourcePipeline,
    convertHsExpr,
    convertModule,
    SourceRegion (..),
    SpannedExpr (..),
    eraseSpannedExpr,
    TopLevelBinding (..),
    ConvertedModule (..),
    ConvertedModuleMetrics (..),
    ConvertObstruction (..),
    convertHaskellSource,
    convertedModuleMetrics,
    hsOpaqueTagName,
    hsPatOpaqueTagName,
    RenderRefusal (..),
    renderHsExpr,
    renderTopLevelBinding,
    renderModuleSource,
    renderRoundTripEquivalent,
  )
where

import Moonlight.EGraph.Introspection.Core.HsExpr.Analysis
import Moonlight.EGraph.Introspection.Core.HsExpr.BinderAlgebra
import Moonlight.EGraph.Introspection.Core.HsExpr.BindingFront
import Moonlight.EGraph.Introspection.Core.HsExpr.Front
import Moonlight.EGraph.Introspection.Core.HsExpr.Laws
import Moonlight.EGraph.Introspection.Core.HsExpr.Sig
import Moonlight.EGraph.Introspection.Core.HsExpr.Spans
import Moonlight.EGraph.Introspection.Core.HsExpr.Unfold
import Moonlight.Pale.Ghc.Expr
