module Moonlight.Cosheaf
  ( CosheafLawFailure (..),
    checkCorestrictionIdentityLawWith,
    checkCorestrictionCompositionDefined,
    checkCorestrictionCompositionLawWith,
    CostalkKey (..),
    FiniteCostalk (..),
    FiniteCosheafAlgebra (..),
    CompiledCorestriction (..),
    FiniteCosheaf,
    fcSite,
    fcSiteIndex,
    fcCostalks,
    fcCorestrictions,
    FiniteCosheafFailure (..),
    finiteCostalkAt,
    finiteCostalkAtObjectKey,
    finiteCostalkValues,
    finiteCostalkKeys,
    finiteCostalkKeyIntSet,
    finiteCostalkValueAt,
    finiteCostalkKeyOf,
    mkFiniteCosheaf,
    compiledCorestrictionFor,
    corestrictCostalkKey,
    finiteCosheafCorestrictions,
    CosectionRepKey (..),
    CosectionClassKey (..),
    CosectionRepresentative (..),
    GlobalCosection (..),
    cosectionRepKeyInt,
    cosectionClassKeyInt,
    cosectionClassOfRepresentativeKey,
    CosheafColimit (..),
    CosheafColimitFailure (..),
    CosheafColimitFactor (..),
    CosheafColimitFactorFailure (..),
    finiteCosheafColimitFromPreparedSupport,
    finiteCosheafColimitFromSupportPlan,
    cosheafColimitRepresentatives,
    cosheafColimitClassOf,
    cosheafColimitEquivalent,
    cosheafColimitMembers,
    cosheafColimitClassKeys,
    factorCosheafColimit,
    cosectionRepresentativeKeyOf,
    cosectionRepresentativeAt,
    CoefficientOps (..),
    PivotOps (..),
    intCoefficientOps,
    integerCoefficientOps,
    rationalCoefficientOps,
    gf2CoefficientOps,
    intUnitPivotOps,
    integerUnitPivotOps,
    rationalPivotOps,
    gf2PivotOps,
    ProvenanceId (..),
    ProvenanceArena (..),
    emptyProvenanceArena,
    appendProvenance,
    lookupProvenance,
    CosheafCoordinate (..),
    BoundaryTerm (..),
    PreparedCosheafBoundary (..),
    PreparedCosheafChain (..),
    PreparedCosheafChainFailure (..),
    buildPreparedCosheafBoundary,
    mkPreparedCosheafChain,
    preparedCosheafBoundaryAt,
    preparedCosheafBasisAt,
    preparedCosheafBoundaryIncidenceAt,
    preparedCosheafBoundaryEntryProvenance,
    CosheafNerveChainKey,
    CosheafChainBasisKey,
    CosheafNerveChain (..),
    CosheafChainCell (..),
    CosheafChainBasisTable (..),
    PreparedFiniteCosheafChain (..),
    CosheafChainFailure (..),
    prepareFiniteCosheafChainFromPreparedSupport,
    prepareFiniteCosheafChainFromSupportPlan,
    cosheafChainBasisAtDegree,
    cosheafChainCellsAtDegree,
    cosheafChainCellByBasisIndex,
    cosheafChainBasisIndexOf,
    cosheafChainBasisKeyAt,
    cosheafBoundaryIncidenceAt,
    verifyCosheafBoundaryNilpotence,
    LinearCosheafChainSpec (..),
    CosheafBoundaryProvenance (..),
    LinearCosheafBoundaryFailure (..),
    LinearCosheafChainFailure (..),
    prepareLinearCosheafChainFromSupportPlan,
    prepareLinearCosheafChainFromLinearCosheafWithSupportPlan,
    prepareLinearCosheafChainFromLinearCosheaf,
    CoverIntersectionCell (..),
    CoverFace (..),
    CoverNervePlan (..),
    CoverChainSpec (..),
    CoverBoundaryProvenance,
    CoverChainFailure (..),
    coverNervePlanFromEffectiveCoverPlan,
    prepareCoverCosheafChain,
    LiftedCosheafChainTerm (..),
    CosheafHomologyWitness (..),
    CosheafHomologyResult (..),
    CosheafHomologyFailure (..),
    cosheafIntegralHomology,
    cosheafIntegralHomologyResult,
    cosheafIntegralHomologyResultWithRepresentatives,
    liftCosheafRepresentative,
    liftCosheafRepresentatives,
    CosheafH0CellKey (..),
    CosheafH0Agreement (..),
    CosheafH0ClassAgreement (..),
    CosheafH0AgreementReport (..),
    CosheafH0Failure (..),
    verifyCosheafH0RankAgreement,
    verifyCosheafH0ClassAgreement,
    verifyPreparedCosheafH0ClassAgreement,
    degreeZeroBoundaryEquivalence,
    LinearCosheafHomologyArtifact (..),
    LinearCosheafHomologyFailure (..),
    linearCosheafHomology,
    homologyGroupsByDegree,
    CoverHomologyArtifact (..),
    CoverHomologyFailure (..),
    coverHomology,
    coverHomologyOfPreparedChain,
    TropicalPDegree (..),
    TropicalBidegree (..),
    TropicalCellKey (..),
    TropicalCell (..),
    TropicalTangentBasis (..),
    TropicalFace (..),
    TropicalCellularComplex (..),
    TropicalCoefficientWitness (..),
    TropicalBoundaryProvenance,
    TropicalCoefficientFailure (..),
    TropicalHomologyFailure (..),
    TropicalHomologyArtifact (..),
    tropicalTangentRank,
    tropicalCellularBoundaryAlgebra,
    tropicalCoefficientChain,
    tropicalHomology,
    tropicalHomologyWithBackend,
    tropicalHomologyGF2,
    CoverCosectionRepresentative (..),
    CoverCosheafCoequalizer (..),
    CoverCosheafFailure (..),
    coverCosheafCoequalizer,
    LocalBasisKey (..),
    LinearCostalk (..),
    linearCostalkDimension,
    LinearCorestriction (..),
    LinearCosheaf,
    lcosSite,
    lcosSiteIndex,
    lcosCostalks,
    lcosCorestrictions,
    LinearCosheafAlgebra (..),
    LinearCosheafFailure (..),
    mkLinearCosheaf,
    linearCostalkAt,
    linearCostalkAtObjectKey,
    linearCorestrictionFor,
    linearCosheafCorestrictions,
    SupportCarrier,
    scHasAny,
    scContains,
    supportCarrierItems,
    supportCarrierCount,
    CosheafSupportCertificate (..),
    CosheafSupportPlan,
    cspMaxDegree,
    cspObjects,
    cspMorphisms,
    cspCostalkKeys,
    cspNerveRows,
    cspChainCells,
    cspFootprintMeasures,
    cspCertificate,
    CosheafSupportFailure (..),
    PreparedCosheafSupport (..),
    cosheafSupportPlanFromKeys,
    prepareCosheafSupport,
    fullFiniteCosheafChainPreparedSupport,
    supportedCorestrictions,
    validateCosheafSupportPlan,
    fullFiniteCosheafChainSupportPlan,
    h0SupportPlan,
    h0PreparedSupport,
    homologyWindowSupportPlan,
    homologyWindowPreparedSupport,
    LinearCosheafSupportCertificate (..),
    LinearCosheafSupportPlan,
    lcspCells,
    lcspFaces,
    lcspCoordinates,
    LinearCosheafSupportFailure (..),
    linearCosheafSupportPlanFromLists,
    validateLinearCosheafSupportPlan,
    fullLinearCosheafSupportPlan,
    CosheafMorsePolicy (..),
    defaultCosheafMorsePolicy,
    CosheafMorsePair (..),
    CosheafMorseMatching (..),
    CosheafMorseHomologyAgreement (..),
    MorseProvenance (..),
    CosheafMorseReduction (..),
    CosheafMorseFailure (..),
    morseReduceCosheafChain,
    CosheafBlockMorsePolicy (..),
    defaultWholeCostalkBlockSchurPolicy,
    CosheafBlockPivotPlan (..),
    CosheafResidualBlock (..),
    BlockSchurMorseProvenance (..),
    CosheafBlockMorseReduction (..),
    CosheafBlockMorseFailure (..),
    blockSchurReduceCosheafChain,
    blockSchurReduceCosheafChainWithPlan,
    MinPlusWeight (..),
    TropicalCostParseFailure (..),
    minPlusZero,
    minPlusOne,
    minPlusFinite,
    minPlusInfinity,
    minPlusAdd,
    minPlusMul,
    minPlusSum,
    minPlusProduct,
    minPlusFromRational,
    parseMinPlusWeight,
    TropicalTransition (..),
    TropicalWeightedTransition (..),
    TropicalCostModel (..),
    TropicalCostTable (..),
    TropicalClassChoice (..),
    TropicalCosectionPlan (..),
    TropicalCosectionFailure (..),
    compileTropicalCostTableFromSupportPlan,
    planTropicalCosections,
    CosheafMorphismKey (..),
    IndexedCosheafMorphism (..),
    CosheafSiteIndex,
    CosheafSiteIndexFailure (..),
    buildCosheafSiteIndex,
    cosheafSiteObjectIndex,
    cosheafIndexedMorphisms,
    cosheafComposableMorphismPairs,
    cosheafCompositionValidationBasis,
    cosheafMorphismKeyOf
  )
where

import Moonlight.Cosheaf.Core
import Moonlight.Cosheaf.Finite
import Moonlight.Cosheaf.Cosection
import Moonlight.Cosheaf.Colimit
import Moonlight.Cosheaf.Chain
import Moonlight.Cosheaf.Chain.Linear
import Moonlight.Cosheaf.Chain.Cover
import Moonlight.Cosheaf.Homology
import Moonlight.Cosheaf.Homology.H0
import Moonlight.Cosheaf.Homology.Linear
import Moonlight.Cosheaf.Homology.Cover
import Moonlight.Cosheaf.Homology.Tropical
import Moonlight.Cosheaf.Cover.Coequalizer
import Moonlight.Cosheaf.Linear
import Moonlight.Cosheaf.Support
import Moonlight.Cosheaf.Support.Linear
import Moonlight.Cosheaf.Reduction.Morse
import Moonlight.Cosheaf.Reduction.BlockSchur
import Moonlight.Cosheaf.Tropical.Cost
import Moonlight.Cosheaf.SiteIndex
