-- | Facade over the semantic differential calculus: Z-set algebra, delta
-- actions, batch\/trace denotation, runtime time\/frontier vocabulary,
-- operators, and the stream calculus; the row\/index plane, physical spine,
-- and qualified finite-map dialect remain surgical imports from their own
-- modules.
module Moonlight.Differential
  ( -- * Z-set algebra
    ZSet,
    IndexedZSet,
    Timed (..),
    zsetEmpty,
    zsetSingleton,
    zsetInsert,
    zsetFromList,
    zsetToAscList,
    zsetLookup,
    zsetDifference,
    zsetNegate,
    zsetUnions,
    zsetNull,
    zsetSize,
    zsetFold,
    indexedZSetEmpty,
    indexedZSetSingleton,
    indexedZSetInsert,
    indexedZSetFromList,
    indexedZSetUnions,
    indexedZSetLookup,
    indexedZSetLookupValue,
    indexedZSetToAscList,
    indexedZSetDifference,
    indexedZSetKeySet,
    indexedZSetFilter,
    indexedZSetNull,
    indexedZSetCellCount,
    indexedZSetFold,

    -- * Delta actions and updates
    DeltaOps,
    deltaApply,
    deltaCombine,
    deltaIdentity,
    deltaIsEmpty,
    deltaApplyMany,
    deltaCombineMany,
    monoidDeltaOps,
    Update (..),

    -- * Runtime time
    FrontierStamp,
    frontierStamp,
    frontierStampWord,
    initialFrontierStamp,
    nextFrontierStamp,
    RuntimeScope,
    runtimeScopePath,
    emptyRuntimeScope,
    enterRuntimeScope,
    leaveRuntimeScope,
    isDescendantOf,
    RuntimeEpoch,
    runtimeEpoch,
    reQuotient,
    reLive,
    RuntimeTime,
    runtimeTime,
    rtContext,
    rtScope,
    rtEpoch,
    rtPhase,
    rtFrontier,
    runtimeTimeSameContext,
    runtimeTimeSameScope,
    runtimeTimeSameScopeLeq,
    runtimeTimeSameScopeLt,
    recontextRuntimeTime,
    retimeRuntimePhase,
    rescopeRuntimeTime,
    enterRuntimeTimeScope,
    leaveRuntimeTimeScope,
    delayRuntimeTimeFeedback,

    -- * Runtime frontiers and capabilities
    RuntimeFrontierKey,
    runtimeFrontierKey,
    runtimeFrontierKeyContext,
    runtimeFrontierKeyScope,
    runtimeFrontierKeyForTime,
    RuntimeFrontier,
    RuntimeAntichain,
    RuntimeCapability,
    RuntimeInvalidCapabilityAdvance (..),
    RuntimeFrontierError (..),
    runtimeCapabilityTime,
    mintRootRuntimeCapability,
    runtimeCapabilityFrontier,
    downgradeRuntimeCapability,
    emptyRuntimeFrontier,
    frontierCutoffForContext,
    frontierCutoffForScope,
    frontierCutoffForTime,
    frontierVisibleAntichain,
    frontierVisibleAntichainForContext,
    frontierVisibleAntichainForScope,
    frontierVisibleMinimums,
    frontierPendingCounts,
    frontierPendingPointstamps,
    frontierPendingInScope,
    frontierPendingAntichain,
    frontierPendingCount,
    frontierInsertPending,
    frontierDeletePending,
    frontierCompletePending,
    frontierAdvanceVisibleMin,
    frontierHasPendingAtOrBefore,
    frontierPendingBeforeVisibleMinimum,
    frontierTimeCompactable,

    -- * Batches
    Batch,
    batchLower,
    batchUpper,
    batchDescription,
    batchRowCount,
    emptyBatch,
    singletonBatch,
    fromUpdates,
    mergeBatch,
    mergeBatches,
    foldBatch,
    foldBatchKey,
    foldBatchKeyRows,
    batchToUpdates,
    batchNull,

    -- * Traces
    Trace,
    TraceFrontierAdvanceError (..),
    traceSince,
    traceUpper,
    traceDescription,
    traceRecentBatches,
    emptyTrace,
    singletonTrace,
    traceFromBatch,
    traceFromBatches,
    traceFromUpdates,
    traceAppendBatch,
    traceAdvanceSince,
    traceAdvanceUpper,
    traceAccumUpTo,
    foldTraceAccumUpTo,
    snapshotTraceBatch,
    foldTrace,
    foldTraceBatches,
    foldTraceBatchRows,
    foldTraceKeyRows,
    foldTraceKey,
    foldTraceKeyThrough,
    foldTraceKeyAfter,
    traceNull,

    -- * Trace descriptions
    TraceDescription,
    TraceDescriptionReadError (..),
    TraceDescriptionAdvanceError (..),
    traceDescriptionLower,
    traceDescriptionUpper,
    traceDescriptionSince,
    traceDescriptionAdvanceSince,
    traceDescriptionAdvanceUpper,
    traceDescriptionReadAt,
    traceDescriptionReadAfter,
    traceDescriptionTimeCompactable,

    -- * Operators
    mapZSet,
    filterZSet,
    indexBy,
    joinIndexed,
    indexedDeltaJoin,
    foldDeltaJoin,
    arrangedKeyZSet,
    indexedDeltaJoinArranged,
    countByKey,
    GroupView,
    GroupChange (..),
    mkGroupView,
    groupViewIntegrated,
    groupViewReduced,
    groupViewAdvance,
    positiveSupportMember,
    distinctZSet,
    distinctDelta,
    SemiNaiveBudget (..),
    SemiNaiveDivergence (..),
    semiNaiveFixpoint,

    -- * Stream calculus
    Stream,
    ScalarLinearMap (..),
    stream,
    streamAt,
    constant,
    mapStream,
    zipWithStream,
    delay,
    differentiate,
    integrate,
    incrementalize,
    applyScalarLinearMap,
    mapScalarLinearStream,

    -- * Locally finite time order
    LocallyFiniteOrder (..),
    RootedLocallyFiniteOrder (..),
    foldMapGroup,
    scaleInteger,
    mobius,
    mobiusProduct,
  )
where

import Moonlight.Differential.Algebra.ZSet
import Moonlight.Differential.Batch
import Moonlight.Differential.Delta
import Moonlight.Differential.Frontier
import Moonlight.Differential.Operator.Aggregate
import Moonlight.Differential.Operator.Fixpoint
import Moonlight.Differential.Operator.Join
import Moonlight.Differential.Operator.Linear
import Moonlight.Differential.Order.LocallyFinite
import Moonlight.Differential.Stream
import Moonlight.Differential.Time
import Moonlight.Differential.Trace
import Moonlight.Differential.Trace.Description hiding (traceDescription)
import Moonlight.Differential.Update
