{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE RoleAnnotations #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE StandaloneKindSignatures #-}

module Moonlight.EGraph.Pure.Context.Internal.Store
  ( ContextEGraph (..),
    AnnotatedDeltaBuckets (..),
    AnnotatedDeltaCache (..),
    AnnotatedDeltaCacheAdvance (..),
    AnnotatedDeltaAdvanceMode (..),
    AnnotatedDeltaFrontier (..),
    AnnotatedRow (..),
    ContextFiber (..),
    ContextPayloadLookupError (..),
    ContextRuntimeState (..),
    emptyContextRuntimeState,
    bumpContextRevision,
  )
where

import Data.IntMap.Strict (IntMap)
import Data.IntMap.Strict qualified as IntMap
import Data.IntSet qualified as IntSet
import Data.Kind (Type)
import Data.Map.Strict (Map)
import Data.Set (Set)
import Data.Set qualified as Set
import Moonlight.Sheaf.Context.Region
  ( ContextRegion,
  )
import Moonlight.EGraph.Pure.Types
  ( ClassId,
    EGraph,
    EGraphRevision,
  )
import Moonlight.EGraph.Pure.Context.Internal.RegionalUnionFind
  ( RegionalUnionFind,
  )
import Moonlight.Sheaf.Context.Core
  ( ContextPropagationReport,
  )
import Moonlight.Sheaf.Context.Site
  ( ClassSupportIndex,
    PreparedContextSite,
  )
import Moonlight.Sheaf.Section.Congruence.Equivalence.Relation
  ( EquivalenceRelation,
  )
import Numeric.Natural
  ( Natural,
  )

-- | Authored context-local delta: the equivalence generated by the unions
-- staged AT this exact context, kept in base-canonical coordinates. Fibers
-- are virtual — the observable relation at a context is derived by
-- accumulating authored deltas over its down-set, never stored. The revision
-- records the base epoch the coordinates were last repaired against; it is a
-- repair stamp, not semantic content, and is excluded from equality.
type ContextFiber :: Type
data ContextFiber = ContextFiber
  { cfRelation :: !(EquivalenceRelation ClassId),
    cfBaseRevision :: !EGraphRevision
  }

instance Eq ContextFiber where
  leftFiber == rightFiber =
    cfRelation leftFiber == cfRelation rightFiber

type ContextEGraph :: Type -> (Type -> Type) -> Type -> Type -> Type
data ContextEGraph owner f a c = ContextEGraph
  { cegBase :: EGraph f a,
    cegSite :: PreparedContextSite owner c,
    cegContextFibers :: Map c ContextFiber,
    cegClassSupport :: ClassSupportIndex owner c,
    cegContextAnalysisDeltas :: Map c (IntMap a),
    cegAnnotatedDeltaCache :: !(AnnotatedDeltaCache owner f),
    cegContextRevision :: !Natural,
    cegRuntimeState :: ContextRuntimeState c
  }

type role ContextEGraph nominal nominal nominal nominal

type AnnotatedRow :: Type -> Type
data AnnotatedRow owner = AnnotatedRow
  { arRootKey :: !Int,
    arChildKeys :: ![Int],
    arRegion :: !(ContextRegion owner)
  }
  deriving stock (Eq, Ord, Show)

type role AnnotatedRow nominal

type AnnotatedDeltaBuckets :: Type -> (Type -> Type) -> Type
data AnnotatedDeltaBuckets owner f = AnnotatedDeltaBuckets
  { adbVariantRowsByTag :: !(Map (f ()) [AnnotatedRow owner]),
    adbAbsorbedRowsByTag :: !(Map (f ()) [AnnotatedRow owner]),
    adbRegionalUnionFind :: !(RegionalUnionFind owner),
    adbInhabitedRegion :: !(ContextRegion owner)
  }

type role AnnotatedDeltaBuckets nominal nominal

deriving stock instance Eq (f ()) => Eq (AnnotatedDeltaBuckets owner f)

deriving stock instance Show (f ()) => Show (AnnotatedDeltaBuckets owner f)

type AnnotatedDeltaFrontier :: (Type -> Type) -> Type
data AnnotatedDeltaFrontier f = AnnotatedDeltaFrontier
  { adfRepresentativeKeys :: !IntSet.IntSet,
    adfVariantRowsByTag :: !(Map (f ()) (Set (Int, [Int]))),
    adfAbsorbedRowsByTag :: !(Map (f ()) (Set (Int, [Int])))
  }

deriving stock instance Eq (f ()) => Eq (AnnotatedDeltaFrontier f)

deriving stock instance Show (f ()) => Show (AnnotatedDeltaFrontier f)

type AnnotatedDeltaAdvanceMode :: Type
data AnnotatedDeltaAdvanceMode
  = AnnotatedDeltaReused
  | AnnotatedDeltaAdvancedRegionally
  | AnnotatedDeltaRecompiledForBaseRevision !EGraphRevision !EGraphRevision
  deriving stock (Eq, Ord, Show)

type AnnotatedDeltaCache :: Type -> (Type -> Type) -> Type
data AnnotatedDeltaCache owner f = AnnotatedDeltaCache
  { adcBaseRevision :: !EGraphRevision,
    adcContextRevision :: !Natural,
    adcBuckets :: !(AnnotatedDeltaBuckets owner f),
    adcDirtyFrontierByContextKey :: !(IntMap (AnnotatedDeltaFrontier f))
  }

type role AnnotatedDeltaCache nominal nominal

deriving stock instance Eq (f ()) => Eq (AnnotatedDeltaCache owner f)

deriving stock instance Show (f ()) => Show (AnnotatedDeltaCache owner f)

type AnnotatedDeltaCacheAdvance :: Type -> (Type -> Type) -> Type
data AnnotatedDeltaCacheAdvance owner f = AnnotatedDeltaCacheAdvance
  { adcaCache :: !(AnnotatedDeltaCache owner f),
    adcaFrontierByContextKey :: !(IntMap (AnnotatedDeltaFrontier f)),
    adcaAdvanceMode :: !AnnotatedDeltaAdvanceMode
  }

type role AnnotatedDeltaCacheAdvance nominal nominal

deriving stock instance Eq (f ()) => Eq (AnnotatedDeltaCacheAdvance owner f)

deriving stock instance Show (f ()) => Show (AnnotatedDeltaCacheAdvance owner f)

type ContextRuntimeState :: Type -> Type
data ContextRuntimeState c = ContextRuntimeState
  { crsDirtyContexts :: !(Set c),
    crsLastRepair :: !(Maybe (ContextPropagationReport c))
  }

emptyContextRuntimeState :: ContextRuntimeState c
emptyContextRuntimeState =
  ContextRuntimeState
    { crsDirtyContexts = Set.empty,
      crsLastRepair = Nothing
    }

bumpContextRevision :: ContextEGraph owner f a c -> ContextEGraph owner f a c
bumpContextRevision contextGraph =
  contextGraph {cegContextRevision = succ (cegContextRevision contextGraph)}
{-# INLINE bumpContextRevision #-}

type ContextPayloadLookupError :: Type -> Type
data ContextPayloadLookupError c
  = MissingContextPayload !c
  deriving stock (Eq, Ord, Show)
