{-# LANGUAGE GHC2024 #-}

-- | Default public face for the relational rewrite stack.
-- Owns the stable user import surface spanning DSL authoring, host/engine
-- execution, matching, application, saturation, extraction, PBPO algebra, and
-- public error types.
-- Contract: semantic authority stays in the stratum modules re-exported here;
-- this module introduces no alternate runtime model.
module Moonlight.Rewrite
  ( -- Signature definition
    K (..),
    SortWitness,
    sortWitness,
    sortWitnessName,
    sortWitnessSortName,
    sameSortWitness,
    Node,
    nodeChildren,
    HTraversable (..),
    hmap,
    RewriteSignature (..),
    deriveRewriteSignature,

    -- Typed terms
    SortName,
    sortName,
    sortNameString,
    SymbolToken,
    symbolToken,
    symbolTokenText,
    TypedVar,
    SomeTypedVar,
    typedVar,
    typedVarName,
    typedVarSort,
    someTypedVarName,
    someTypedVarSort,
    Term,
    var,
    node,

    -- Rule DSL
    RuleBody,
    Extension,
    extension,
    rootExtension,
    globalExtension,
    Guard,
    NoGuardAtom,
    RewriteGuardAtom (..),
    RuleScope (..),
    ContextRef (..),
    RuleBinders,
    bindTypedVar,
    bind,
    forall_,
    (==>),
    (=:=),
    (=/=),
    atom_,
    not_,
    all_,
    any_,
    when_,
    whenExt_,
    requires_,
    forbids_,
    at,
    globally,

    -- Names
    RuleName,
    RuleNameError (..),
    mkRuleName,
    ruleNameString,
    ContextName,
    ContextNameError (..),
    contextName,
    contextNameString,

    -- Programs
    MacroPath,
    Program,
    ProgramM,
    program,
    rule,
    context,
    macro,
    compose,
    (>>>),

    -- Host
    ClassId,
    classIdKey,
    Host,
    HostTerm (..),
    HostProgramResult (..),
    HostRebuildResult (..),
    emptyHost,
    hostFromTerm,
    hostFromTerms,
    hostFromNodes,
    hostFromNodeClasses,
    hostCanonicalClass,
    hostClassCount,
    hostNodeClasses,
    hostClassWitness,
    hostLookupTermClass,
    hostRevision,
    hostSections,
    hostSectionsFromClasses,
    rebuildHostBarrier,
    runHostRewriteProgram,

    -- Engine
    Rules,
    Engine,
    compile,
    prepare,
    engineHost,
    replaceHost,
    setContext,
    removeContext,

    -- Matching
    MatchVar,
    matchVarOrdinal,
    matchVarName,
    matchVarSort,
    RewriteTarget (..),
    MatchQuery (..),
    Match,
    matchTarget,
    matchRule,
    matchRoot,
    matchBindings,
    matchRevision,
    matchSubstitution,
    match,

    -- Single-step application
    ApplyConfig (..),
    defaultApplyConfig,
    ApplyRejection (..),
    ApplyStatus (..),
    ApplyResult (..),
    apply,

    -- Saturation
    SaturationConfig (..),
    defaultSaturationConfig,
    SaturationRound (..),
    SaturationResult (..),
    saturate,
    ProofRetention (..),
    defaultProofRetention,
    RewriteRunConfig (..),
    defaultRewriteRunConfig,
    RewriteRestriction (..),
    RewriteRunMetric (..),
    RewriteRunMetrics (..),
    RewriteRunLimits,
    RewriteRunStats,
    Limit (..),
    Count (..),
    RewriteRunLimit (..),
    RewriteRunError (..),
    noRewriteRunLimits,
    defaultRewriteRunLimits,
    limitToBoundedInt,
    limitToOverflowSentinel,

    -- Extraction
    Cost (..),
    ExtractRoundLimit (..),
    ExtractConfig (..),
    defaultExtractConfig,
    Extracted,
    extractedTerm,
    extractedClass,
    extractedCost,
    ExtractError (..),
    extract,
    extractWith,

    -- PBPO+ algebra
    PBPORule,
    pbpoRuleMeta,
    pbpoRuleLeftLeg,
    pbpoRuleRightLeg,
    pbpoRuleLeftTyping,
    pbpoRuleInterfaceTyping,
    pbpoRuleContextLeg,
    pbpoRuleInterface,
    pbpoRuleLeft,
    pbpoRuleRight,
    pbpoRuleContextInterface,
    pbpoRuleContextType,
    PBPOLegName (..),
    PBPOEndpointPosition (..),
    PBPOEndpointRef (..),
    PBPOEndpointConstraint (..),
    PBPOTypingSquareSide (..),
    PBPORuleObstruction (..),
    PBPOLegs,
    plLeftLeg,
    plRightLeg,
    plLeftTyping,
    plInterfaceTyping,
    plContextLeg,
    mkPBPORule,
    PBPOMatch,
    pbpoMatchMonic,
    pbpoMatchAdherence,
    PBPOStepFailure (..),
    PBPOStep,
    pbpoStepHost,
    pbpoStepContext,
    pbpoStepContextToPrior,
    pbpoStepContextTyping,
    pbpoStepMediator,
    pbpoStepContextToHost,
    pbpoStepReplacementToHost,
    pbpoStepRule,
    PBPOUntypedStep,
    pbpoUntypedHost,
    pbpoUntypedComplement,
    pbpoUntypedContextToHost,
    pbpoUntypedReplacementToHost,
    pbpoUntypedRule,
    applyPBPOPlus,
    applyPBPO,
    identityTypedRule,
    admitPBPOUnit,

    -- Errors
    HostBuildError (..),
    prettyHostBuildError,
    RelationalProgramError (..),
    prettyRelationalProgramError,
  )
where

import Moonlight.Rewrite.Algebra
  ( PBPOLegs,
    PBPOMatch,
    PBPORule,
    PBPOLegName (..),
    PBPOEndpointPosition (..),
    PBPOEndpointRef (..),
    PBPOEndpointConstraint (..),
    PBPOTypingSquareSide (..),
    PBPORuleObstruction (..),
    PBPOStep,
    PBPOStepFailure (..),
    PBPOUntypedStep,
    admitPBPOUnit,
    applyPBPO,
    applyPBPOPlus,
    identityTypedRule,
    mkPBPORule,
    pbpoRuleContextInterface,
    pbpoRuleContextLeg,
    pbpoRuleContextType,
    pbpoRuleInterface,
    pbpoRuleInterfaceTyping,
    pbpoRuleLeft,
    pbpoRuleLeftLeg,
    pbpoRuleLeftTyping,
    pbpoRuleMeta,
    pbpoRuleRight,
    pbpoRuleRightLeg,
    pbpoMatchAdherence,
    pbpoMatchMonic,
    pbpoStepContext,
    pbpoStepContextToHost,
    pbpoStepContextToPrior,
    pbpoStepContextTyping,
    pbpoStepHost,
    pbpoStepMediator,
    pbpoStepReplacementToHost,
    pbpoStepRule,
    pbpoUntypedComplement,
    pbpoUntypedContextToHost,
    pbpoUntypedHost,
    pbpoUntypedReplacementToHost,
    pbpoUntypedRule,
    plContextLeg,
    plInterfaceTyping,
    plLeftLeg,
    plLeftTyping,
    plRightLeg,
  )
import Moonlight.Rewrite.DSL
  ( ContextName,
    ContextNameError (..),
    ContextRef (..),
    Extension,
    Guard,
    HTraversable (..),
    K (..),
    MacroPath,
    NoGuardAtom,
    Node,
    Program,
    ProgramM,
    RewriteGuardAtom (..),
    RewriteSignature (..),
    RuleBinders,
    RuleBody,
    RuleScope (..),
    SomeTypedVar,
    SortName,
    SortWitness,
    SymbolToken,
    Term,
    TypedVar,
    all_,
    any_,
    at,
    atom_,
    bind,
    bindTypedVar,
    compose,
    context,
    contextName,
    contextNameString,
    deriveRewriteSignature,
    extension,
    forbids_,
    forall_,
    globalExtension,
    globally,
    hmap,
    macro,
    node,
    nodeChildren,
    not_,
    program,
    requires_,
    rootExtension,
    rule,
    someTypedVarName,
    someTypedVarSort,
    sameSortWitness,
    sortName,
    sortNameString,
    sortWitness,
    sortWitnessName,
    sortWitnessSortName,
    symbolToken,
    symbolTokenText,
    typedVar,
    typedVarName,
    typedVarSort,
    var,
    whenExt_,
    when_,
    (=/=),
    (=:=),
    (==>),
    (>>>),
  )
import Moonlight.Rewrite.Relational.Front
  ( ApplyConfig (..),
    ApplyRejection (..),
    ApplyResult (..),
    ApplyStatus (..),
    ClassId,
    Engine,
    Host,
    HostBuildError (..),
    HostTerm (..),
    HostProgramResult (..),
    HostRebuildResult (..),
    Match,
    MatchQuery (..),
    MatchVar,
    RelationalProgramError (..),
    RewriteTarget (..),
    Rules,
    SaturationConfig (..),
    SaturationResult (..),
    SaturationRound (..),
    Cost (..),
    ExtractRoundLimit (..),
    ExtractConfig (..),
    ExtractError (..),
    Extracted,
    apply,
    classIdKey,
    compile,
    defaultExtractConfig,
    defaultApplyConfig,
    defaultSaturationConfig,
    emptyHost,
    engineHost,
    extract,
    extractWith,
    extractedClass,
    extractedCost,
    extractedTerm,
    hostCanonicalClass,
    hostClassCount,
    hostClassWitness,
    hostFromNodeClasses,
    hostFromNodes,
    hostFromTerm,
    hostFromTerms,
    hostLookupTermClass,
    hostNodeClasses,
    hostRevision,
    hostSections,
    hostSectionsFromClasses,
    match,
    matchBindings,
    matchRoot,
    matchRule,
    matchRevision,
    matchSubstitution,
    matchTarget,
    matchVarName,
    matchVarOrdinal,
    matchVarSort,
    prepare,
    prettyHostBuildError,
    prettyRelationalProgramError,
    rebuildHostBarrier,
    removeContext,
    replaceHost,
    runHostRewriteProgram,
    saturate,
    setContext,
  )
import Moonlight.Rewrite.Relational
  ( Count (..),
    Limit (..),
    RewriteRunLimit (..),
    RewriteRunLimits,
    RewriteRunMetric (..),
    RewriteRunMetrics (..),
    RewriteRunStats,
    defaultRewriteRunLimits,
    limitToBoundedInt,
    limitToOverflowSentinel,
    noRewriteRunLimits,
    RewriteRestriction (..),
    RewriteRunConfig (..),
    RewriteRunError (..),
    defaultRewriteRunConfig,
  )
import Moonlight.Rewrite.System
  ( RuleName,
    RuleNameError (..),
    mkRuleName,
    ruleNameString,
  )
import Moonlight.Rewrite.ProofContext
  ( ProofRetention (..),
    defaultProofRetention,
  )
