module Moonlight.Homology.Chain
  ( HomologicalDegree (..),
    incrementDegree,
    decrementDegree,
    EulerCharacteristic (..),
    PersistencePair (..),
    RepresentativeChain (..),
    RepresentativeCycle,
    RepresentativeCocycle,
    HarmonicBasisElement (..),
    ExactRepresentativeClass (..),
    TopologyWitness (..),
    emptyTopologyWitness,
    mergeTopologyWitness,
    mergeTopologyWitnessChecked,
    topologyRepresentativeCycles,
    topologyRepresentativeCocycles,
    topologyWitnessFromBetti,
    BettiReducer (..),
    BettiCapability,
    computeBettiNumbers,
    TopologyWitnessReducer (..),
    TopologyWitnessCapability,
    computeTopologyWitness,
    EffectiveHomology,
    sourceComplex,
    reducedComplex,
    reductionWitness,
    finiteBoundary,
    mkEffectiveHomology,
    HomologyLaw (..),
    NonEffectiveCause (..),
    HomologyFailure (..),
    FiniteAbelianTorsion,
    mkFiniteAbelianTorsion,
    torsionFromHomologyGroup,
    finiteAbelianInvariants,
    normalizeTorsionOrders,
    finiteAbelianSummandCount,
    finiteAbelianCyclicSummandMultiplicity,
    finiteAbelianFilteredCardinality,
    finiteAbelianCardinality,
    finiteAbelianExponent,
    finiteAbelianOrderSupport,
    finiteAbelianPrimaryOrderSupport,
    finiteAbelianExactOrderElementCount,
    isPrime,
    matchesOptional,
    DegreeSelection (..),
    GradedAggregation (..),
    GradedQuery (..),
    selectAllDegrees,
    selectDegree,
    degreeSelectionFromMaybe,
    combineSelectedQuery,
    preserveDegreewiseQuery,
    matchesDegreeSelection,
    enumerateDegreeIndexed,
    lookupDegreeIndexed,
    selectDegreeIndexed,
    selectGradedMembers,
    countGradedMembers,
    DegreeSelection (..),
    GradedAggregation (..),
    GradedQuery (..),
    selectAllDegrees,
    selectDegree,
    degreeSelectionFromMaybe,
    combineSelectedQuery,
    preserveDegreewiseQuery,
    enumerateDegreeIndexed,
    lookupDegreeIndexed,
    selectDegreeIndexed,
    selectGradedMembers,
    countGradedMembers,
    directProductQuery,
    degreewiseUnionQuery,
    GradedTorsionFamily,
    mkGradedTorsionFamily,
    gradedTorsionPresent,
    gradedTorsionAtDegree,
    gradedTorsionCombined,
    gradedTorsionOrderSupport,
    gradedTorsionPrimaryOrderSupport,
    HomologyGroup (..),
    LinearCombination,
    LinearCombinationArithmetic (..),
    numArithmetic,
    ringArithmetic,
    normalizeWith,
    composeWith,
    addWith,
    subtractWith,
    identityWith,
    checkLawWith,
    HomologyPhase (..),
    RequirePhase2,
    RequirePhase4,
    requirePhase2Witness,
    requirePhase4Witness,
    ChainMap (..),
    ChainHomotopy (..),
    Reduction (..),
    ReductionWitness,
    checkedReduction,
    ReductionLawContext (..),
    ReductionViolation (..),
    Validation (..),
    ReductionValidation,
    ReductionChecks (..),
    mkReductionWitness
  )
where

import Moonlight.Homology.Pure.Chain as X
import Moonlight.Homology.Pure.Matrix.Reducer as X
import Moonlight.Homology.Pure.Effective as X
import Moonlight.Homology.Pure.Failure as X
import Moonlight.Homology.Pure.FiniteAbelian as X
import Moonlight.Homology.Pure.Graded.Query as X
import Moonlight.Homology.Pure.GradedTorsion as X
import Moonlight.Homology.Pure.Group as X
import Moonlight.Homology.Pure.LinearCombination as X
import Moonlight.Homology.Pure.Phase as X
import Moonlight.Homology.Pure.Reductions as X
