module Moonlight.Homology.Sequence
  ( MayerVietorisReducer (..),
    MayerVietorisCapability,
    mayerVietoris,
    FiltrationFunction,
    Bidegree,
    mkBidegree,
    bidegreeFromTotalDegree,
    bidegreeCoordinates,
    bidegreeFiltrationDegree,
    bidegreeComplementaryDegree,
    bidegreeTotalDegree,
    targetBidegreeAfterDifferential,
    FormalMap (..),
    RationalFormalMap,
    SpectralEntry (..),
    RationalSpectralEntry,
    SpectralPage (..),
    RationalSpectralPage,
    SpectralChain,
    SpectralFamily (..),
    RationalSpectralFamily,
    SpectralAdvance (..),
    SpectralCapability,
    nextPage,
    computeRationalSpectralFamily,
    computeRationalSpectralPages,
    stableSpectralPage,
    convergenceDepth,
    isKPassParseable,
    graphLaplacian,
    laplacianEntry,
    weightedGraphLaplacian,
    weightedGraphSparseLaplacian,
    SparseSpectralConfig (..),
    defaultSparseSpectralConfig,
    weightedGraphSpectralModes,
    weightedGraphSparseSpectralModes,
    weightedGraphSpectralGap,
    gapFromModes,
    leadingModeTransport,
    smallestEigenpairs,
    largestEigenpairs,
    powerIteration,
    traceMatrix,
    subtractFromDiagonal,
    basisVector,
    BasisBlock (..),
    BlockSchurPivot (..),
    BlockPivotOps (..),
    integerUnimodularBlockPivotOps,
    rationalBlockPivotOps,
    gf2BlockPivotOps,
    BlockSchurTranscript (..),
    BlockSchurReduction (..),
    BlockSchurFailure (..),
    blockSchurReduceWith
  )
where

import Moonlight.Homology.Pure.Sequence.Exact as X
import Moonlight.Homology.Pure.Sequence.Spectral as X
import Moonlight.Homology.Pure.Topology.BlockSchur as X
import Moonlight.Homology.Pure.Topology.Spectral as X
