module Moonlight.Sheaf.Site
  ( SiteBoundaryAlgebra (..),
    SiteComplexScaffold (..),
    SiteComplexScaffoldError (..),
    SiteMorseReduction (..),
    defaultSiteCellHeuristic,
    grothendieckBoundaryAlgebra,
    grothendieckBoundaryCells,
    grothendieckChainComplexFromSite,
    mkGrothendieckComplexScaffold,
    mkNerveComplexScaffold,
    mkSiteComplexScaffoldFromCells,
    mkSiteComplexScaffold,
    nerveBoundaryAlgebra,
    reduceSiteComplex,
    reduceSiteComplexWith,
    siteBoundaryCells,
    siteChainComplexFromSite,
    CheckedMorphism (..),
    PullbackSquare (..),
    CoveringFamily,
    CoverConstructionError (..),
    SiteConstructionError (..),
    SiteLawFailure (..),
    mkCoveringFamily,
    coverTarget,
    coverArrows,
    coverSources,
    coverSize,
    Site (..),
    isIdentityMorphism,
    siteMorphismUniverse,
    siteRestrictionMorphisms,
    identityCover,
    pullbackCoverAlong,
    transitiveCover,
    FiniteCoverBasis (..),
    FiniteCoverBasisFailure (..),
    mkFiniteCoverBasis,
    finiteCoversAt,
    finiteCoverPlanForCover,
    finiteCanonicalCoverPlan,
    finiteIdentityCoverAt,
    finitePullbackCoverPlan,
    finiteCommonRefinementPlan,
    ContextCoverBasis (..),
    ContextArrow (..),
    ContextCover,
    ContextCoverError (..),
    contextCoverFromSources,
    allContextMorphisms,
    identityContextArrow,
    composeContextArrows,
    pullbackContextSquare,
    mkContextArrow,
    ContextGeneratorCover (..),
    contextClosure,
    ContextPairStrategy (..),
    contextDepth,
    latticeContextsBelow,
    overlappingContextPairs,
    downwardContextPairsFromGenerators,
    downwardPairsByStrategy,
    reflexiveDownwardPairsByStrategy,
    ContextPresentation (..),
    ContextPresentationSystem (..),
    contextPresentation,
    contextPresentationWith,
    contextPresentationPairs,
    contextPresentationReflexivePairs,
    ExecutionTransition (..),
    ExecutionVertex (..),
    ExecutionComplex (..),
    ExecutionComplexError (..),
    executionComplex,
    executionTransitionCount,
    executionVertexCount,
    FiniteMeetSiteSpec (..),
    FiniteMeetSite,
    FiniteMeetMorphism,
    FiniteMeetSiteBuildError (..),
    finiteMeetMorphism,
    finiteMeetRefines,
    finiteMeetSiteCells,
    finiteMeetSiteRefinements,
    finiteMeetSiteCovers,
    finiteMeetSiteMeet,
    mkFiniteMeetSite,
    GrothendieckCategory,
    GrothendieckCell,
    GrothendieckCellKey (..),
    GrothendieckFaceMorphism,
    GrothendieckMor (..),
    GrothendieckOb (..),
    GrothendieckSimplexKey (..),
    GrothendieckSite,
    grothendieckCategory,
    grothendieckCategoryFromPresentation,
    grothendieckCellDimension,
    grothendieckCellKey,
    grothendieckCellMorphisms,
    grothendieckCellSingleMorphism,
    grothendieckCellSimplex,
    grothendieckFaceMorphismFaceIndex,
    grothendieckFaceMorphismKind,
    grothendieckFaceMorphismOrientation,
    grothendieckFaceMorphismSource,
    grothendieckFaceMorphismTarget,
    baseGrothendieckMorphisms,
    grothendieckMorphisms,
    grothendieckNerve,
    grothendieckObjects,
    grothendieckSiteCellsAtDimension,
    grothendieckSiteBasis,
    grothendieckSiteCells,
    grothendieckSiteDepth,
    grothendieckSiteFaceMorphisms,
    grothendieckSiteSourceNerve,
    grothendieckZeroCellFromPresentation,
    grothendieckZeroCellByObject,
    grothendieckSimplexKey,
    mkGrothendieckSite,
    mkGrothendieckSiteFromCoverBasis,
    mkGrothendieckSiteFromCoverBasisWindow,
    mkGrothendieckSiteWindow,
    GrothendieckCompositor (..),
    GrothendieckTwoMor (..),
    GrothendieckNilpotentSystem (..),
    GrothendieckStructuralSummary (..),
    summarizeGrothendieckSystem,
    InterfaceDirectionEstimate (..),
    InterfaceMeasure (..),
    InterfaceName,
    MorphismInterface (..),
    interfaceNameFromString,
    interfaceNameFromText,
    interfaceNameText,
    FiniteSiteMap,
    ContinuousSiteMap,
    SiteMapFailure (..),
    CoverImageFailure (..),
    finiteSiteMapSource,
    finiteSiteMapTarget,
    siteMapObjectImage,
    siteMapMorphismImage,
    continuousFiniteSiteMap,
    coverImageAt,
    mkFiniteSiteMap,
    mkContinuousSiteMap,
    CellKey (..),
    FaceKind (..),
    FaceMorphism,
    NerveCell,
    NerveSite,
    NerveSiteAlgebra (..),
    NerveSiteConstructionError (..),
    SimplexKey (..),
    faceMorphismFaceIndex,
    faceMorphismKind,
    faceMorphismOrientation,
    faceMorphismSource,
    faceMorphismTarget,
    faceKindFor,
    mkNerveSite,
    mkNerveSiteDenseWindow,
    mkNerveSiteFromRowPlan,
    mkNerveSiteWCOJWindow,
    mkNerveSiteWindow,
    nerveCellKey,
    nerveCellSimplex,
    nerveSiteBasis,
    nerveSiteCategory,
    nerveSiteCells,
    nerveSiteDepth,
    nerveSiteSourceNerve,
    restrictNerveSiteToCellKeys,
    siteCellsAtDimension,
    siteFaceMorphisms,
    SheafPhase (..),
    RequireStalked,
    RequireConsistent,
    RequireResolved,
    CoverSlotKey (..),
    CoverSlot (..),
    EffectiveCoverPlan,
    EffectiveCoverPlanFailure (..),
    PullbackCoverSlotPlan (..),
    PullbackCoverPlan (..),
    CrossCoverOverlapPlan (..),
    CommonRefinementPlan (..),
    CoverId (..),
    OverlapPlan (..),
    CoverPlan (..),
    SitePlans (..),
    SitePlanBuildError (..),
    effectiveCoverFamily,
    effectiveCoverSlots,
    effectiveCoverOverlapPlans,
    effectiveCoverSlotKeys,
    effectiveCoverSlotArrows,
    effectiveCoverSlotSources,
    effectiveCoverSlotCount,
    prepareEffectiveCoverPlan,
    identityEffectiveCoverPlan,
    preparePullbackCoverPlan,
    pullbackEffectiveCoverPlanAlong,
    prepareCommonRefinementPlan,
    emptySitePlans,
    prepareSitePlans,
    siteCoverPlansAt,
    siteCoverPlanById,
    PolynomialPresentation (..),
    SystemMorphismPosition (..),
    SystemObjectPosition (..),
    systemMorphismPolynomialPresentation,
    systemObjectPolynomialPresentation,
    SiteRestrictionWitness (..),
    SiteRestrictionBuildError (..),
    siteRestrictionStalkAlgebra,
    buildGrothendieckRestrictions,
    buildGrothendieckRestrictionsWithStalkCache,
    buildNerveRestrictions,
    NerveRowSource (..),
    SkeletonRowPlan (..),
    DenseNerveArrangement,
    DenseNerveMorphismOption,
    DenseNerveArrangementError (..),
    nerveSimplexFace,
    skeletonRowPlan,
    truncatedSkeletonRowPlan,
    prepareDenseNerveArrangement,
    denseNerveArrangementObjectCount,
    denseNerveArrangementObjectAt,
    denseNerveArrangementMorphismsFromOrdinal,
    denseNerveMorphismOptionValue,
    denseNerveMorphismOptionTargetOrdinal,
    denseOrdinalNerveRowSource,
    denseOrdinalSkeletonRowPlan,
    denseOrdinalSkeletonRowPlanWithDepth,
    simplicialNerveRowSource,
    wcojNerveRowSource,
    rowSourceToTruncatedNerve,
    denseArrangementCategory,
    CompositionWitness (..),
    FaceStalkProjectionError (..),
    InterfaceDomain (..),
    InterfaceMismatch (..),
    InterfaceStalk (..),
    InterfaceStalkSignature (..),
    WitnessClass (..),
    interfaceStalkAlgebra,
    interfaceStalkExactEq,
    interfaceStalkSignature,
    grothendieckStalkFromCell,
    reducedFaceMorphisms,
    stalkFromCell,
    stalkFromSourceAndMorphisms,
    targetStalkForFace,
    projectInterfaceFaceMorphisms,
    witnessClass,
    LinearizedRestrictionModel,
    InterfaceStalkBasisAtom (..),
    buildLinearizedRestrictionModel,
    linearizedRestrictionComparableRestrictions,
    linearizedRestrictionStalkDimensions,
    interfaceStalkBasisAtoms,
    interfaceStalkBasisLinearization,
    AnalyzableSystem (..),
    LatticeAnalyzableSystem,
    ContextOrdinalSystem (..),
    siteLawFailures,
    checkCompositionClosureLaw,
    checkLeftIdentityLaw,
    checkRightIdentityLaw,
    checkAssociativityLaw,
    checkPullbackSquareCommutativityLaw,
    checkIdentityCoverLaw,
    checkPullbackStabilityLaw,
    checkTransitivityLaw,
    allCompositionClosureFailures,
    allLeftIdentityFailures,
    allRightIdentityFailures,
    allAssociativityFailures,
    allPullbackSquareCommutativityFailures,
    allIdentityCoverFailures,
    allPullbackStabilityFailures,
    allTransitivityFailures,
  )
where

import Moonlight.Sheaf.Site.Analysis.Scaffold
import Moonlight.Sheaf.Site.Class
import Moonlight.Sheaf.Site.CoverBasis.Finite
import Moonlight.Sheaf.Site.Context
import Moonlight.Sheaf.Site.Context.Cover
import Moonlight.Sheaf.Site.Context.GeneratorCover
import Moonlight.Sheaf.Site.Context.Pairs
import Moonlight.Sheaf.Site.Context.Presentation
import Moonlight.Sheaf.Site.System.Execution
import Moonlight.Sheaf.Site.Construction.FiniteMeet
import Moonlight.Sheaf.Site.Grothendieck
import Moonlight.Sheaf.Site.Grothendieck.Category
import Moonlight.Sheaf.Site.Grothendieck.Summary
import Moonlight.Sheaf.Site.Interface.Types
import Moonlight.Sheaf.Site.Construction.Map
import Moonlight.Sheaf.Site.Construction.Nerve
import Moonlight.Sheaf.Site.Phase
import Moonlight.Sheaf.Site.Plan
import Moonlight.Sheaf.Site.System.Polynomial
import Moonlight.Sheaf.Site.Stalk.Restriction
import Moonlight.Sheaf.Site.Skeleton.RowSource
import Moonlight.Sheaf.Site.Stalk.Interface
import Moonlight.Sheaf.Site.Stalk.Interface.Linearization
import Moonlight.Sheaf.Site.System
import Moonlight.Sheaf.Site.Class.Validation
