module Moonlight.EGraph.Pure.Extraction
  ( CostAlgebra (..),
    AnalysisCostAlgebra (..),
    costOnly,
    depthCost,
    liftCostAlgebra,
    ExtractionClass,
    extractionClass,
    extractionClassAnalysis,
    extractionClassNodes,
    ExtractionTable,
    extractionTable,
    extractionClasses,
    extractionCanonicalClass,
    StableExtractionSnapshot,
    stableExtractionSnapshotFromEGraph,
    stableExtractionSnapshotTable,
    ExtractionFixpointBudget (..),
    ExtractionConvergenceReport (..),
    ExtractionChoiceCache,
    eccRevision,
    eccTable,
    eccChoices,
    ExtractionCacheObstruction (..),
    extractionChoiceCacheFromStableGraph,
    advanceExtractionChoiceCache,
    extractionChoiceCacheSection,
    extractCached,
    extractAllCached,
    ExtractionResult (..),
    ExtractionChoiceSection (..),
    extractChoiceSection,
    extractChoiceSectionBounded,
    extendChoiceSectionWithGraphClasses,
    extractFromChoiceSection,
    extractAllFromChoiceSection,
    extractFromTable,
    extractFromTableBounded,
    extractAllFromTable,
    extractAllFromTableBounded,
    extract,
    extractBounded,
    extractAll,
    extractAllBounded,
    extractWithAnalysis,
    extractWithAnalysisBounded,
    extractAllWithAnalysis,
    extractAllWithAnalysisBounded,
    extractChoicesBounded,
    termSize,
    termCost,
  )
where

import Moonlight.EGraph.Pure.Extraction.Algebra
import Moonlight.EGraph.Pure.Extraction.Cache
import Moonlight.EGraph.Pure.Extraction.Compile
import Moonlight.EGraph.Pure.Extraction.Core
