-- Boundary note: this package is a consumer of the generic sheaf and
-- saturation surfaces.  Core/Update/Proof and
-- Context.Update delegates to Moonlight.Sheaf.Context.*,
-- Moonlight.Sheaf.Section.*, Moonlight.Rewrite.Proof,
-- and Moonlight.Saturation.Context.Match.*.  Per-context class/enode incidence
-- is represented as a generic finite category plus NerveSite; saturation keeps
-- owning ProjectionSection, QueryRegistry, and match-state storage.

module Moonlight.EGraph.Pure.Context
  ( ContextEGraph,
    ContextRuntimeState (..),
    cegBase,
    cegSite,
    cegLattice,
    ContextFiber (..),
    cegContextFibers,
    contextAuthoredUnionPairs,
    cegClassSupportIndex,
    cegContextAnalysisDeltas,
    cegContextRevision,
    cegRuntimeState,
    ContextEGraphObstructionFailure (..),
    ContextIncidenceMaterializationError (..),
    ContextPayloadLookupError (..),
    ContextRestrictionMismatchError (..),
    cachedContextPayloadFor,
    requireCachedContextPayloadFor,
    checkedContextRestrictionMismatchesAt,
    materializeIncidenceCategoryFromSnapshot,
    materializeIncidenceSiteFromSnapshot,
    RebaseScope,
    ContextMergePlan,
    ContextRebaseBatch,
    ContextRebaseReport (..),
    ContextMutationTrace (..),
    emptyContextMutationTrace,
    contextMutationTraceFromBase,
    appendContextMutationTrace,
    contextMutationTraceEffect,
    contextMutationTraceTouchedKeys,
    contextPreparedObjects,
    contextCachedObjectsForExecution,
    activateContext,
    contextVisibleClassKeys,
    contextRepresentativeAt,
    contextAnalysisValueAt,
    deriveContextAnalysisDeltaAtKey,
    ambientRepresentativeAnalysisFor,
    ambientRepresentativeAnalysisValuesFor,
    materializeAmbientPayloadFor,
    materializeContextPayloadFor,
    lookupContextPayload,
    graphLiveCanonicalClassMap,
    baseCanonicalClassMap,
    withEmptyContextEGraph,
    emptyContextEGraphFromSite,
    beginContextRebaseBatch,
    contextRebaseBatchBaseGraph,
    contextRebaseBatchSite,
    contextRebaseBatchClassSupportIndex,
    contextRebaseBatchTrace,
    contextRebaseBatchDirtyContexts,
    contextMerge,
    globalMerge,
    ContextDeltaError (..),
    ContextRepairScope (..),
    stageSupportClass,
    stageENodeWithSupport,
    stageTermWithSupport,
    stageTermGlobally,
    stageTermsGlobally,
    stageTermAtContext,
    planContextMerges,
    stageContextMerges,
    stageGlobalMerge,
    prepareContextProjectionAt,
    contextRepairScopeFromCachedObjects,
    prepareContextRebuildForScope,
    commitContextRebaseBatch,
    rebaseAffectedContexts,
    rebaseContextGraphAtContexts,
    rebaseContextGraphWithSupport,
  )
where

import Moonlight.EGraph.Pure.Context.Update
  ( ContextDeltaError (..),
    ContextRepairScope (..),
    ContextRebaseBatch,
    ContextMergePlan,
    ContextRebaseReport (..),
    ContextMutationTrace (..),
    RebaseScope,
    appendContextMutationTrace,
    beginContextRebaseBatch,
    commitContextRebaseBatch,
    contextMerge,
    contextRebaseBatchBaseGraph,
    contextRebaseBatchSite,
    contextRebaseBatchClassSupportIndex,
    contextRebaseBatchDirtyContexts,
    contextRebaseBatchTrace,
    contextMutationTraceEffect,
    contextMutationTraceFromBase,
    contextMutationTraceTouchedKeys,
    withEmptyContextEGraph,
    emptyContextEGraphFromSite,
    emptyContextMutationTrace,
    globalMerge,
    rebaseAffectedContexts,
    rebaseContextGraphAtContexts,
    rebaseContextGraphWithSupport,
    prepareContextProjectionAt,
    contextRepairScopeFromCachedObjects,
    prepareContextRebuildForScope,
    planContextMerges,
    stageENodeWithSupport,
    stageContextMerges,
    stageGlobalMerge,
    stageSupportClass,
    stageTermAtContext,
    stageTermGlobally,
    stageTermsGlobally,
    stageTermWithSupport,
  )
import Moonlight.EGraph.Pure.Context.Core
  ( ContextEGraph,
    ContextRuntimeState (..),
    cegBase,
    cegSite,
    cegLattice,
    ContextFiber (..),
    cegContextFibers,
    contextAuthoredUnionPairs,
    cegClassSupportIndex,
    cegContextAnalysisDeltas,
    cegContextRevision,
    cegRuntimeState,
    ContextEGraphObstructionFailure (..),
    ContextIncidenceMaterializationError (..),
    ContextPayloadLookupError (..),
    ContextRestrictionMismatchError (..),
    cachedContextPayloadFor,
    requireCachedContextPayloadFor,
    checkedContextRestrictionMismatchesAt,
    contextCachedObjectsForExecution,
    activateContext,
    contextVisibleClassKeys,
    contextRepresentativeAt,
    contextAnalysisValueAt,
    deriveContextAnalysisDeltaAtKey,
    ambientRepresentativeAnalysisFor,
    ambientRepresentativeAnalysisValuesFor,
    materializeAmbientPayloadFor,
    materializeContextPayloadFor,
    lookupContextPayload,
    contextPreparedObjects,
    materializeIncidenceCategoryFromSnapshot,
    materializeIncidenceSiteFromSnapshot,
    graphLiveCanonicalClassMap,
    baseCanonicalClassMap,
  )
