-- Boundary note: this package is a consumer of the generic sheaf and
-- saturation surfaces.  Core/Update/Proof and
-- Context.Update delegates to Moonlight.Sheaf.Context.*,
-- Moonlight.Sheaf.Section.*, Moonlight.Rewrite.Proof,
-- and Moonlight.Saturation.Context.Match.*.  Per-context class/enode incidence
-- is represented as a generic finite category plus NerveSite; saturation keeps
-- owning ProjectionSection, QueryRegistry, and match-state storage.

module Moonlight.EGraph.Pure.Context
  ( ContextEGraph,
    cegSite,
    ContextPayloadLookupError (..),
    checkedContextRestrictionMismatchesAt,
    materializeIncidenceCategoryFromSnapshot,
    materializeIncidenceSiteFromSnapshot,
    RebaseScope,
    ContextMergePlan,
    ContextRebaseBatch,
    ContextRebaseReport (..),
    ContextMutationTrace (..),
    emptyContextMutationTrace,
    contextMutationTraceFromBase,
    appendContextMutationTrace,
    contextMutationTraceEffect,
    contextMutationTraceTouchedKeys,
    contextPreparedObjects,
    contextCachedObjectsForExecution,
    activateContext,
    contextVisibleClassKeys,
    contextRepresentativeAt,
    contextAnalysisValueAt,
    materializeAmbientPayloadFor,
    materializeContextPayloadFor,
    emptyContextEGraph,
    emptyContextEGraphFromSite,
    beginContextRebaseBatch,
    contextRebaseBatchBaseGraph,
    contextRebaseBatchSite,
    contextRebaseBatchClassSupportIndex,
    contextRebaseBatchTrace,
    contextRebaseBatchDirtyContexts,
    contextMerge,
    globalMerge,
    ContextDeltaError (..),
    stageSupportClass,
    stageENodeWithSupport,
    stageTermWithSupport,
    stageTermGlobally,
    stageTermsGlobally,
    stageTermAtContext,
    planContextMerges,
    stageContextMerges,
    stageGlobalMerge,
    commitContextRebaseBatch,
    rebaseAffectedContexts,
    rebaseContextGraphAtContexts,
    rebaseContextGraphWithSupport,
  )
where

import Moonlight.EGraph.Pure.Context.Update
  ( ContextDeltaError (..),
    ContextRebaseBatch,
    ContextMergePlan,
    ContextRebaseReport (..),
    ContextMutationTrace (..),
    RebaseScope,
    appendContextMutationTrace,
    beginContextRebaseBatch,
    commitContextRebaseBatch,
    contextMerge,
    contextRebaseBatchBaseGraph,
    contextRebaseBatchSite,
    contextRebaseBatchClassSupportIndex,
    contextRebaseBatchDirtyContexts,
    contextRebaseBatchTrace,
    contextMutationTraceEffect,
    contextMutationTraceFromBase,
    contextMutationTraceTouchedKeys,
    emptyContextEGraph,
    emptyContextEGraphFromSite,
    emptyContextMutationTrace,
    globalMerge,
    rebaseAffectedContexts,
    rebaseContextGraphAtContexts,
    rebaseContextGraphWithSupport,
    planContextMerges,
    stageENodeWithSupport,
    stageContextMerges,
    stageGlobalMerge,
    stageSupportClass,
    stageTermAtContext,
    stageTermGlobally,
    stageTermsGlobally,
    stageTermWithSupport,
  )
import Moonlight.EGraph.Pure.Context.Core
  ( ContextEGraph,
    cegSite,
    ContextPayloadLookupError (..),
    checkedContextRestrictionMismatchesAt,
    contextCachedObjectsForExecution,
    activateContext,
    contextVisibleClassKeys,
    contextRepresentativeAt,
    contextAnalysisValueAt,
    materializeAmbientPayloadFor,
    materializeContextPayloadFor,
    contextPreparedObjects,
    materializeIncidenceCategoryFromSnapshot,
    materializeIncidenceSiteFromSnapshot,
  )
