module Moonlight.Pale.Ghc.Expr
  ( HsVarRef (..),
    BinderAnn (..),
    HsOpaqueTag (..),
    HsPatOpaqueTag (..),
    HsPatF (..),
    patBinders,
    traversePatBinders,
    LetMode (..),
    LetRecursion (..),
    LetProvenance (..),
    ScopeId,
    ScopeIdFailure (..),
    ScopeCtx (..),
    ScopeIndex,
    ScopeIndexFailure (..),
    ScopeLookupFailure (..),
    ScopeEulerLabel (..),
    FreeScopeSummary,
    mkScopeId,
    scopeIdKey,
    rootScopeId,
    mkScopeIndex,
    scopeIndexRoot,
    scopeParentId,
    scopeDepthOf,
    scopeIsAncestorOf,
    scopeComparable,
    scopeLca,
    scopeCtxLeq,
    scopeCtxMeet,
    scopeCtxJoin,
    scopeObservedCount,
    scopeObservedContexts,
    scopeTopCtx,
    scopeBottomCtx,
    binderIntroScope,
    binderSiteScope,
    emptyFreeScopeSummary,
    singletonFreeScopeSummary,
    mergeFreeScopeSummary,
    mergeFreeScopeSummaryBy,
    mergeFreeScopeSummaryByEither,
    deleteFreeScopeSummary,
    freeScopeSummaryContains,
    freeScopeSummarySize,
    freeScopeSummaryToList,
    freeScopeSupportAnchor,
    NormalizedLit (..),
    normalizeHsLit,
    NormalizedOverLit (..),
    normalizeHsOverLit,
    NormalizedFieldLabel (..),
    normalizeFieldLabel,
    NormalizedTypeText (..),
    NormalizedArithSeq (..),
    HsExprF (..),
    HsStmtF (..),
    HsGuardStmtF (..),
    GuardedAltF (..),
    ScopedExpr (..),
    eraseScopedExpr,
    SpannedExpr (..),
    eraseSpannedExpr,
    HsExprTag (..),
    TagSignature (..),
    tagSignatureFromTag,
    tagSignatureMember,
    matchesHsExprPattern,
    matchHsExprPatternSubstitution,
    instantiateHsExprPattern,
    SourceRegion (..),
    TopLevelBinding (..),
    ConvertedModule (..),
    ConvertedModuleMetrics (..),
    ConvertObstruction (..),
    convertHsExpr,
    convertModule,
    convertHaskellSource,
    convertedModuleMetrics,
    hsOpaqueTagName,
    hsPatOpaqueTagName,
    RenderRefusal (..),
    renderHsExpr,
    renderReadableHsExpr,
    renderTopLevelBinding,
    renderReadableTopLevelBinding,
    renderGeneratedTopLevelBinding,
    renderModuleSource,
    renderRdrName,
    renderRoundTripEquivalent,
  )
where

import Moonlight.Pale.Ghc.Expr.Convert
import Moonlight.Pale.Ghc.Expr.NameRender (renderRdrName)
import Moonlight.Pale.Ghc.Expr.Opaque
import Moonlight.Pale.Ghc.Expr.Render
import Moonlight.Pale.Ghc.Expr.Scope
import Moonlight.Pale.Ghc.Expr.Syntax
