module Moonlight.EGraph.Fuzzy.Simplicial
  ( SimplexId (..),
    ParallelTagFingerprint (..),
    ParallelFaceKey (..),
    EdgeKind (..),
    TruncatedFaceComplex,
    faceComplexSimplicesAtDimension,
    faceComplexFaceAtDimension,
    TriangleRequirement (..),
    ParallelRequirement (..),
    ParallelEvidence (..),
    ParallelBlockRegistryValidationError (..),
    ParallelShapeValidationError (..),
    SimplicialBackendValidationError (..),
    BlockCanonicalization (..),
    ParallelBlockRegistry,
    mkParallelBlockRegistry,
    CanonicalizationRegistry,
    mkCanonicalizationRegistry,
    ParallelShapeAlgebra,
    mkParallelShapeAlgebra,
    validateParallelPatternShape,
    validateParallelClassShape,
    SimplicialBackend,
    mkSimplicialBackend,
    SimplicialPattern (..),
    LiftedEGraph (..),
    HomotopicSubstitution (..),
    liftPatternSimplicially,
    liftEGraphSimplicially,
    homotopicMatch,
    homotopicMatchWithRoots,
    homotopicMatchCompiledWithRoots,
    homotopicMatchCompiledWithRootFilter,
  )
where

import Moonlight.EGraph.Fuzzy.Simplicial.Backend.Internal
  ( HomotopicSubstitution (..),
    SimplicialBackend,
    SimplicialBackendValidationError (..),
    homotopicMatch,
    homotopicMatchWithRoots,
    homotopicMatchCompiledWithRoots,
    homotopicMatchCompiledWithRootFilter,
    mkSimplicialBackend,
  )
import Moonlight.EGraph.Fuzzy.Simplicial.Complex.Internal
  ( EdgeKind (..),
    ParallelTagFingerprint (..),
    SimplexId (..),
    TruncatedFaceComplex,
    faceComplexFaceAtDimension,
    faceComplexSimplicesAtDimension,
  )
import Moonlight.EGraph.Fuzzy.Simplicial.Graph.Internal
  ( LiftedEGraph (..),
    liftEGraphSimplicially,
  )
import Moonlight.EGraph.Fuzzy.Simplicial.Pattern.Internal
  ( SimplicialPattern (..),
    liftPatternSimplicially,
  )
import Moonlight.EGraph.Fuzzy.Simplicial.Shape
  ( BlockCanonicalization (..),
    CanonicalizationRegistry,
    ParallelBlockRegistry,
    ParallelBlockRegistryValidationError (..),
    ParallelEvidence (..),
    ParallelFaceKey (..),
    ParallelRequirement (..),
    ParallelShapeAlgebra,
    ParallelShapeValidationError (..),
    TriangleRequirement (..),
    mkCanonicalizationRegistry,
    mkParallelBlockRegistry,
    mkParallelShapeAlgebra,
    validateParallelClassShape,
    validateParallelPatternShape,
  )
