module Moonlight.Sheaf.Surface.ObstructionSurfaceSpec
  ( tests,
  )
where

import Data.Set (Set)
import Data.Set qualified as Set
import Moonlight.Sheaf.Surface.Support
  ( ExportSurfaceLock (..),
    assertExportSurfaceLocked,
  )
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.HUnit (Assertion, testCase)

tests :: TestTree
tests =
  testGroup
    "obstruction API surface"
    [ testCase "Moonlight.Sheaf.Obstruction exports are explicit and locked" testObstructionExportsAreLocked
    ]

testObstructionExportsAreLocked :: Assertion
testObstructionExportsAreLocked =
  assertExportSurfaceLocked
    ExportSurfaceLock
      { eslLabel = "Moonlight.Sheaf.Obstruction",
        eslBarrelPrefix = "module Moonlight.Sheaf.Obstruction.",
        eslSourceCandidates =
          [ "src-obstruction/Moonlight/Sheaf/Obstruction.hs",
            "foundation/moonlight-sheaf/src-obstruction/Moonlight/Sheaf/Obstruction.hs",
            "compiler/foundation/moonlight-sheaf/src-obstruction/Moonlight/Sheaf/Obstruction.hs"
          ],
        eslExpectedExports = expectedObstructionExports,
        eslForbiddenExport = const False
      }

expectedObstructionExports :: Set String
expectedObstructionExports =
  Set.fromList
    [ "StructuralMismatchData (..)",
      "ConditionFailureData (..)",
      "ContextBarrierData (..)",
      "RestrictionBarrierData (..)",
      "RestrictionLookupFailureData (..)",
      "PropagationBarrierData (..)",
      "EquivalenceLookupFailureData (..)",
      "Obstruction (..)",
      "ContextualObstructionStore (..)",
      "obstructionReport",
      "whyNotMerged",
      "obstructionReportWith",
      "whyNotMergedWith",
      "buildOneLayer",
      "buildCycleLayer",
      "nerveFromAdjacency",
      "nerveFromSupport",
      "cycleReportFromEdgeAssignment",
      "holonomyCoverCohomologyReport",
      "orientedCycleEdges",
      "tupleWitnessCoverCohomologyReport",
      "assignmentWitnessCoverCohomologyReport",
      "boundaryAt",
      "rankGapLowerBound",
      "rankUpperBoundary2",
      "supportCellsFromBasis",
      "supportCellsFromRepresentatives",
      "CohomologyObservation (..)",
      "runCohomologyObservation",
      "analyzeCohomologicalRegion",
      "kernelVerdictSummary",
      "analyzeKernelAcceptedRegion",
      "analyzeFreshCohomologicalRegion",
      "analyzeExactSummary",
      "analyzeRefinedSummary",
      "cohomologicalWitnessFromLift",
      "emptyObstructionWitness",
      "modalityCoverageWitness",
      "obstructionWitnessFor",
      "matchesFromCohomologicalLift",
      "exactMatchFromSection",
      "occurrenceDomainConstraints",
      "syntheticOccurrenceConstraintId",
      "exactCoverageFromLift",
      "exactCoverageSupportsObstruction",
      "buildCohomologicalLift",
      "morphismCells",
      "restrictionIndexFor",
      "orientedRestrictionIndexFor",
      "degreeToInt",
      "buildCohomologicalRegionSupport",
      "validateOccurrenceDomains",
      "ObstructionCacheKey (..)",
      "CohomologicalCache",
      "emptyCohomologicalCache",
      "lookupCachedObstruction",
      "insertCachedObstruction",
      "insertCachedObstructionForDependencies",
      "invalidateCachedObstructions",
      "CarrierPlan (..)",
      "RegionCarrierPlan",
      "carrierPlanFromList",
      "representedCarrierPlanFromList",
      "regionCarrierPlanFromList",
      "carrierPlanItems",
      "carrierPlanCount",
      "CachePolicy (..)",
      "EnvironmentCacheKey (..)",
      "environmentFingerprintFromCachePolicy",
      "SectionCertificationAlgebra (..)",
      "mkSectionCertificationAlgebraWithCachePolicy",
      "mkSectionCertificationAlgebraWithCapabilitiesAndCachePolicy",
      "IndexedEnvironment",
      "emptyIndexedEnvironment",
      "indexedEnvironmentFromList",
      "insertEnvironmentBinding",
      "lookupEnvironmentBinding",
      "environmentBindingKeys",
      "IndexedEnvironmentBuilder (..)",
      "IndexedEnvironmentAlgebra",
      "emptyIndexedEnvironmentAlgebra",
      "registerEnvironmentBuilder",
      "indexedEnvironmentAlgebraFromList",
      "environmentBuilderKeys",
      "buildIndexedEnvironment",
      "ObstructionEnvironmentAlgebra (..)",
      "CohomologicalExactMatchEvidence (..)",
      "CohomologicalExactMatch (..)",
      "CohomologicalExactEvidenceCoverage",
      "CohomologicalRootCoverage",
      "CohomologicalExactCoverage (..)",
      "StaticComponentIndex",
      "LiveMicrosupport",
      "liveMicrosupportPruningEvidence",
      "nonCriticalNodesFromLiveMicrosupport",
      "pruningGatesFromLiveMicrosupport",
      "recomputeLiveMicrosupport",
      "staticComponentIndex",
      "equalityConstraintsBy",
      "guardEqualityConstraintsBy",
      "RelationConstraintBuild (..)",
      "RelationConstraintPlan (..)",
      "RelationLoweringAlgebra (..)",
      "lowerRelationConstraint",
      "lowerRelationConstraintPlan",
      "zipWithConstraintIds",
      "MicrosupportEnrichment (..)",
      "computeMicrosupportEnrichment",
      "computeNerveMicrosupportEnrichment",
      "microsupportNodeFilter",
      "microsupportCandidateRegionFilter",
      "microsupportCandidateRegionSeedFilter",
      "nerveSiteToPoset",
      "LoweringSite (..)",
      "LoweringGap (..)",
      "data MissingReferenceGap",
      "data UnsupportedAnchorGap",
      "ModalityContribution (..)",
      "CapabilityLabelAlgebra (..)",
      "emptyCapabilityLabelAlgebra",
      "discreteCapabilityLabelAlgebra",
      "CapabilityRow",
      "emptyCapabilityRow",
      "capabilityRowFromList",
      "capabilityRowMembers",
      "finiteCapabilityRowAlgebra",
      "mapCapabilityLabelAlgebra",
      "CapabilitySupport (..)",
      "CapabilityEnvironment (..)",
      "emptyCapabilityEnvironment",
      "TypedCapabilitySupport (..)",
      "TypedCapabilityEnvironment (..)",
      "emptyTypedCapabilityEnvironment",
      "lowerCapabilityEnvironment",
      "lowerCapabilityEnvironmentWithGaps",
      "capabilityModality",
      "typedCapabilityModality",
      "obstructionModality",
      "obstructionModalityWithReification",
      "ObstructionModality (..)",
      "ModalityRegistry",
      "emptyModalityRegistry",
      "registerModality",
      "modalityRegistryFromList",
      "modalityRegistryKeys",
      "modalityRegistryProjection",
      "modalityRegistryProjectionConflicts",
      "modalityRegistryReification",
      "evaluateModalities",
      "evaluateModalityRegistry",
      "SheafModalityTag (..)",
      "SheafModalityCoverage",
      "mkSheafModalityCoverage",
      "SheafModalityKey (..)",
      "sheafModalityTagFromKey",
      "validateModalityCoverage",
      "validateModalityCoverageWithEnvironmentKeys",
      "LaplacianGapThreshold",
      "mkLaplacianGapThreshold",
      "laplacianGapThresholdValue",
      "LaplacianPruning (..)",
      "profileLaplacianPruning",
      "ExactCoverageBudget (..)",
      "defaultExactCoverageBudget",
      "profileExactCoverageBudget",
      "CohomologicalPolicy (..)",
      "CohomologicalProfile (..)",
      "profilePolicy",
      "SectionCoordinate (..)",
      "structuralCoordinate",
      "relationCoordinate",
      "RelationProjectionMode (..)",
      "RelationProjectionPolicy",
      "RelationProjectionConflict (..)",
      "emptyRelationProjectionPolicy",
      "relationProjectionPolicyFor",
      "combineRelationProjectionPolicies",
      "resolveRelationProjectionMode",
      "separateRelationFlavors",
      "SectionProjection",
      "projectConstraintCoordinates",
      "sectionCoordinateProjection",
      "defaultSectionProjection",
      "PruningEvidence (..)",
      "PruningEvidenceFamily (..)",
      "CohomologicalPruningFootprint (..)",
      "CohomologicalPruningCertificate",
      "RetainedCohomologicalRegion (..)",
      "CohomologicalPruningObstruction (..)",
      "CohomologicalPruningGates (..)",
      "gatesFromEvidence",
      "buildPruningGates",
      "seedPruningGate",
      "regionPruningGate",
      "keepSeed",
      "keepRegion",
      "retainedRegionFromDecision",
      "retainRegion",
      "seedFootprint",
      "regionFootprint",
      "cohomologicalFootprintMeasures",
      "prunedSeeds",
      "prunedRegions",
      "pruningEvidenceFamily",
      "pruningEvidenceFamilyEvidence",
      "pruningFamilyNonCriticalNodes",
      "pruningFamilyRelevantOrdinals",
      "pruningFamilyObstructedNodes",
      "microsupportResultPruningEvidence",
      "RegionExactness (..)",
      "RegionAnalysisOutcome (..)",
      "RegionExactCoverage",
      "recExactness",
      "recCoverage",
      "mkRegionExactCoverage",
      "RegionTraversalSummary (..)",
      "skippedRegionCoverage",
      "regionCoverageFromSectionCoverage",
      "RelationEvidence (..)",
      "SectionMatch (..)",
      "SectionCoverage (..)",
      "SectionFeasibilityFailure (..)",
      "SectionCoverageSummary (..)",
      "sectionCoverageFeasibility",
      "mapSectionCoverage",
      "mapSectionCoverageGaps",
      "bimapSectionCoverage",
      "firstSectionCoverageGap",
      "foldSectionCoverage",
      "summarizeSectionCoverage",
      "renderSectionCoverage",
      "projectSectionCoverageWith",
      "projectSectionCoverage",
      "SectionAssignment (..)",
      "sectionBindings",
      "sectionBinding",
      "SectionReification (..)",
      "emptySectionReification",
      "sectionReification",
      "reifySectionAssignment",
      "relationEvidenceFromAssignment",
      "ExactSearchCost (..)",
      "exactSearchCostWithSeed",
      "exactSearchCostWithin",
      "enumerateProjectedSectionsWithSeed",
      "enumerateSectionMatchesWithSeed",
      "enumerateSectionMatchesWithinBudgetWithSeed",
      "CohomologicalAnchor",
      "CohomologicalCoordinate",
      "SubstrateRegion",
      "SubstrateExactMatch",
      "SubstrateExactEvidence",
      "SubstrateRegionCoverage",
      "SubstrateRegionSummary",
      "SubstrateWitness",
      "SubstrateCache",
      "SubstrateCacheKey",
      "SubstrateRootCoverage",
      "CohomologicalRegionSupport (..)",
      "CohomologicalLift (..)",
      "CohomologicalSupportAlgebra (..)",
      "CohomologicalSubstrate (..)",
      "environmentFingerprintFor",
      "normalizeCohomologicalRegion",
      "regionDependencyKeys",
      "cacheKeyForRegion",
      "RegionScale (..)",
      "RegionNodeId (..)",
      "Anchor (..)",
      "CandidateRegion (crRoot, crMembers, crDepth, crScale, crNodeId, crFingerprint)",
      "CandidateRegionSeed (crsRoot, crsNodeId, crsContextOrdinal, crsFingerprint)",
      "CandidateRegionSeedKey (..)",
      "mkCandidateRegion",
      "mkCandidateRegionWithNode",
      "mkCandidateRegionSeed",
      "mkCandidateRegionSeedWithContext",
      "candidateRegionSeedKey",
      "candidateRegionSeedFromKey",
      "CandidateStalk (..)",
      "OccurrenceId (..)",
      "ConstraintId (..)",
      "CycleId (..)",
      "ExactLabelCode (..)",
      "anchorDomain",
      "RelationFlavor (..)",
      "ExactConstraint (EqualityConstraint, GuardConstraint, RelationConstraint)",
      "data FactConstraint",
      "data ProvenanceConstraint",
      "data ProofConstraint",
      "data CapabilityConstraint",
      "ObstructionCell ( RegionRootCell, OccurrenceCell, EqualityConstraintCell, GuardConstraintCell, RelationConstraintCell, CycleCell )",
      "data FactConstraintCell",
      "data ProvenanceConstraintCell",
      "data ProofConstraintCell",
      "data CapabilityConstraintCell",
      "ExpandedObstructionCell ( ExpandedRootCell, ExpandedOccurrenceCell, ExpandedEqualityConstraintCell, ExpandedGuardConstraintCell, ExpandedRelationConstraintCell, ExpandedCycleCell )",
      "data ExpandedFactConstraintCell",
      "data ExpandedProvenanceConstraintCell",
      "data ExpandedProofConstraintCell",
      "data ExpandedCapabilityConstraintCell",
      "ExpandedStalk (..)",
      "expandedStalkAlgebra",
      "ExpandedMorphism (..)",
      "expandedRestriction",
      "zeroCellForAnchor",
      "NerveEdge (..)",
      "OrientedNerveEdge (..)",
      "CoverNerve (..)",
      "WitnessStalk",
      "WitnessMismatch (..)",
      "witnessCoefficients",
      "witnessSingleton",
      "witnessUnion",
      "witnessNegate",
      "witnessSubtract",
      "witnessIsZero",
      "witnessMagnitude",
      "witnessStalkAlgebra",
      "TupleWitnessBasis (..)",
      "TupleWitnessStalk",
      "TupleWitnessMismatch",
      "tupleWitnessFromDescent",
      "edgeTupleWitnessFromDescent",
      "AssignmentWitnessBasis (..)",
      "AssignmentWitnessStalk",
      "AssignmentWitnessMismatch",
      "assignmentWitnessFromDescent",
      "edgeAssignmentWitnessFromDescent",
      "CycleDescriptor (..)",
      "ObstructionLift (..)",
      "ObstructionReason (..)",
      "ObstructionWitness (..)",
      "C1LocalConflict (..)",
      "Nerve1Cochain (..)",
      "NervePotential (..)",
      "CycleExactness (..)",
      "H1Class (..)",
      "CycleCohomologyReport (..)",
      "AnalysisTruncationCause (..)",
      "AnalysisCompleteness (..)",
      "CoverCohomologyReport (..)",
      "QuotientCoverCohomologyReport",
      "AssignmentCoverCohomologyReport",
      "TupleWitnessCoverCohomologyReport",
      "AssignmentWitnessCoverCohomologyReport",
      "ModalityCoverage (..)",
      "isCompleteModalityCoverage"
    ]
